### PR TITLE
Add blacken-docs and pycln pre-commit hooks

### PR DESCRIPTION
**Pull request by Skylion007**
## Description

* Applies [blacken-docs](https://github.com/asottile/blacken-docs) and therefore black code formatting to the RST documentation.
* Applies [pycln](https://github.com/hadialqattan/pycln) and removes unused imports.
* Fixes syntax highlighting blocks that were improperly set.
* I added the associated pre-commit hooks as well.

## Suggested changelog entry:

```rst
* Add blacken-docs pre-commit hook
* Add pycln pre-commit hook and remove unused imports 
* Fix highlighting hints and errors in RST docs
```

### CODE REVIEW

**Comment by henryiii** [comment]
I'd be fine to add the pinning. Black doesn't really change that fast (or practically at all), so a slightly older docs format is unlikely to clash with the main format. We'd get auto fixes, for example,w with that.

**Comment by Skylion007** [comment]
@henryiii Okay, I'll add it.

**Comment by Skylion007** [comment]
@henryiii Yeah, I would feel even better though if someone could add a CI check that checks that version match in the pre-commit.yaml though like we do for other version checks.

**Comment by henryiii** [comment]
I wasn't aware of pycln, looks useful. :)

**Comment by Skylion007** [comment]
@henryiii @rwgk Okay, this PR is ready to go unless anyone has objections?

**Review by henryiii — APPROVED** [review]

**Pull request merged**
