### PR TITLE
refactor: followup to #2569

### PR DESCRIPTION
**Pull request by henryiii**
Followup to #2569

### CODE REVIEW

**Comment by YannickJadoul** [comment]
Would you mind giving this a test, @asobhy-qnx?

**Comment by asobhy-qnx** [comment]
I do not mind testing it again. I did already test it before creating the first pull request. double checking does not hurt. I will let you know the results.

**Comment by henryiii** [comment]
Fantastic, @asobhy-qnx, thank you!

**Comment by YannickJadoul** [comment]
Thanks! :-)

**Comment by YannickJadoul** [comment]
@henryiii, one of these tests is running GCC 4.8, right?

Ah, but we don't actually test if that works, ofc :-/ We don't have a test that the right branch actually compiles for libstdc++?

**Comment by henryiii** [comment]
We don't do any cross-compiling, that is, no GCC with libc++ or Clang with libstdc++ (I'm slightly misusing the term there), so we don't know if it gets detected correctly - and yes, we don't know if this branch gets ignored, unless there's a test throwing this (not sure what triggers it?).

@asobhy-qnx You are compiling from GCC with libc++, right? So the only way this could "fail" for you is if the branch is enabled; that is, if `__GLIBCXX__` is defined, I would assume by GCC itself.

**Comment by asobhy-qnx** [comment]
I thought __GLIBCXX__ == libc++ I was completely wrong __GLIBCXX__ == libstdc++ and this is why it was not working for me.

It did work and I was able to build the examples.

**Comment by henryiii** [comment]
That's why double checking is useful. :) Merging then!

**Comment by YannickJadoul** [comment]
Ah, great! Thanks, @asobhy-qnx :-)

**Comment by asobhy-qnx** [comment]
test for __GBLICXX__ done and was successful

**Comment by YannickJadoul** [comment]
Thanks for checking, @asobhy-qnx!

**Pull request merged**
