### PR TITLE
Enable dynamic attribute support for Pypy >= 6

### PR DESCRIPTION
**Pull request by inducer**
According to my experiments, the code that's disabled by the conditional on Pypy appears to work just fine on (at least) Pypy 6.0.

### CODE REVIEW

**Comment by wjakob** [comment]
I'm hesitant to merge this if there is no coverage. Would you mind adding a PyPy 6.x configuration to Travis?

**Comment by inducer** [comment]
Done. It does not pass, but he failures look largely unrelated to the change I made:

https://travis-ci.org/pybind/pybind11/jobs/421779974

**Comment by bstaletic** [comment]
Rebase onto master. The failure was fixed last night.

**Comment by inducer** [comment]
Thanks for taking a look. Still failing, with much the same failures:

https://travis-ci.org/pybind/pybind11/jobs/421907230

**Comment by wjakob** [comment]
hm :-|  -- any thoughts on what the deal is with the other PyPy issue?

**Comment by inducer** [comment]
No clue, sorry.

**Comment by wjakob** [comment]
Not sure I understand, what does "this" refer to in your sentence? Attribute support?

**Comment by xuhdev** [comment]
@wjakob Yes... sorry for the confusion.

**Comment by rwgk** [comment]
Hi Andreas, there was a recent upgrade to use PyPy 7.3 on travis, e.g. here is a random recent result (bottom of page): https://travis-ci.org/github/pybind/pybind11/builds/698654908
Is this PR still relevant?

**Comment by lopuhin** [comment]
@rwgk I think this PR is still relevant and now it seems closer to merging (after travis changes are removed), as these changes https://github.com/pybind/pybind11/pull/1494/files#diff-cb87ad4a7288c536c9adc5a5694134ca still look relevant to me.

**Comment by inducer** [comment]
IMO, #2146 by @isuruf supersedes this. I contains this change (and adds a related test). I'm happy to close this as long as there's a chance that #2146 will get merged.

**Comment by wjakob** [comment]
It will be merged soon, I will close this PR then.

**Pull request closed without merging**
