### PR TITLE
Add handle::repr() method

### PR DESCRIPTION
**Pull request by aldanor**
A very simple PR, add `handle::repr()` method.

### CODE REVIEW

**Comment by aldanor** [comment]
Oh great, Windows and Python 2 strike back 🔫 

https://bugs.python.org/issue706263

**Comment by dean0x7d** [comment]
This would be very easy to confuse with Python's regular `print` which does something entirely different. It's the same problem that `py::str` currently has, i.e. it doesn't do what you would expect from Python (which makes it easier to make a mistake). Besides, the [overloaded `operator<<`](https://github.com/pybind/pybind11/blob/master/include/pybind11/stl.h#L188) already does half of this as just `std::cout << obj;`. Perhaps introduce a `repr` function which can be used as `std::cout << py::repr(obj)`?

**Comment by aldanor** [comment]
Makes sense, agreed. So the only real missing part is `repr()` then.

I've added `handle::repr()`, if this looks ok, I'll squash this.

**Comment by aldanor** [comment]
Squashed.

**Comment by wjakob** [comment]
LGTM, thanks!

**Pull request merged**
