### PR TITLE
Make header files viewable in IDEs

### PR DESCRIPTION
**Pull request by drufat**
Add header files to the target created in pybind11_add_module in order to make them viewable in the project tree of IDEs.

### CODE REVIEW

**Comment by wjakob** [comment]
Actually what I meant is to modify the pybind11_add_module function itself ;)

**Comment by dean0x7d** [comment]
If the headers are added in `pybind11_add_module` then they will be displayed as a (modifiable) part of any module which uses pybind11. But they should probably be read-only headers for user modules. The headers are only when working on the library itself, so the tests-only solution is probably best.

**Comment by wjakob** [comment]
I don't think Visual Studio & friends allow you to reference a header in a read only way. What is the "tests-only solution" you refer to?

**Comment by dean0x7d** [comment]
I mean what's currently committed: the headers are only added to the test module which should be enough.

As for IDEs, they scan files differently depending on whether the are part of the project or just appear as an include. I mostly use CLion and it distinguishes "Project Source and Headers" from "Libraries". It's been a while since I've used the IDE part of Visual Studio, but I seem to recall to it does something similar. Marking a dependency as the main part of the project seems a little strange to me.

**Comment by drufat** [comment]
Yes, the header files will have different locations depending on whether they have been installed, or whether they are still in the source folder. So they cannot be included in the function itself because that information will depend on the context from which it is called. 

I modified the new commit to be just this:
```
file(GLOB PYBIND11_HEADERS ../include/*.h)
pybind11_add_module(pybind11_tests pybind11_tests.cpp ${PYBIND11_TEST_FILES} ${PYBIND11_HEADERS})
```

**Comment by drufat** [comment]
Does this look good to you?

**Comment by dean0x7d** [comment]
Just tried it in CLion: it works for me (but I can't say I'm a fan of `GLOB`).

**Comment by drufat** [comment]
What do you suggest I use in its place? I cannot use the original PYBIND11_HEADERS because it is a different relative path from root.

**Comment by wjakob** [comment]
You could prepend the cmake variable for the current source directory (CMAKE_CURRENT_SOURCE_DIR or something like that), which (I think) is absolute.

**Comment by drufat** [comment]
Done.

**Comment by wjakob** [comment]
I committed a variant of this patch since the code here potentially didn't generate the right include paths when recursively included in another project (CMAKE_SOURCE_DIR vs CMAKE_CURRENT_SOURCE_DIR)..

**Pull request closed without merging**
