### PR TITLE
WIP cross module exception ODR experiments

### PR DESCRIPTION
**Pull request by rwgk**
## Description
**Guessing** what could be behind #4105

Local testing passes. Let's see what happens in the CI.

## Suggested changelog entry:

```rst

```

### CODE REVIEW

**Comment by henryiii** [comment]
This has to be built with different versions of pybind11, right? - see #4282 where I'm setting up a way to do that.

**Comment by rwgk** [comment]
I saw the emails from your PR but haven't looked at it yet.

I'm trying to emulate ODR, so that the test is simpler. This is following what worked for #4022.

I don't know if and how cross-module exceptions are different or special, compared to the type_caster situation, but it's a starting point I'm familiar with.

I'm not certain this will become a permanent test, or only inform something else after I learn something here.

**Comment by rwgk** [comment]
The CI succeeds on all platforms. — I was hoping for at least some failures, because very clearly, the definitions of `class evolving` in cross_module_exception_odr_1.cpp & cross_module_exception_odr_2.cpp are very different (modeling #1895). The MSVC errors in the first attempt prove that that class is DLL-exported. Why does that obvious ODR violation not break anything? What am I missing or overlooking?

**Comment by henryiii** [comment]
I believe ODR is UB, and in this case, because everything's pretty much the same, UB is simply the (un)expected behavior?

**Comment by rwgk** [comment]
Quick note, I cannot explain properly at the moment, but at least on my Linux workstation the finding is conclusive:

When adding this to conftest.py
```
import sys
sys.setdlopenflags(0x100 | 0x2)  # RTLD_GLOBAL | RTLD_NOW
```

* it still works if I run test_cross_module_exception_odr_1.py or test_cross_module_exception_odr_2.py separately,
* but running the 2nd after the 1st, I'm seeing a `Fatal Python error: Segmentation fault`, or `RuntimeError: D` instead of `v2` when running with gdb (i.e. the behavior of the same binaries is different, running normally, or with gdb).

I.e. classical UB.

Preliminary conclusion: `RTLD_LOCAL` is another layer of hiding the symbols that otherwise lead to ODR.

I still have to figure out what the situation is under macOS and Windows.

**Comment by rwgk** [comment]
@henryiii @Skylion007 @Lalaland @jbms does anyone know: what's the equivalent of `RTLD_GLOBAL` on Windows?

From looking around I'm thinking it doesn't exist, Windows only has behavior similar to `RTLD_LOCAL`, but I didn't find a source that clearly says that.

Based on the CI for 42c9554, it looks like `RTLD_GLOBAL` (nicely!) breaks Linux, but not macOS. — CAVEAT: I didn't go through with a comb yet.

I'm still not clear how exactly symbols are resolved when pybind11 extensions are `dlopen`ed, but it seem the default `RTLD_LOCAL` makes the combination of #2999 and #1895 safe.

Everything I'm saying here is preliminary and could use multiple sets of extra eyes.

I also started another super simple experiment under #4284.

**Comment by jbms** [comment]
I don't believe Windows has anything like rtld_global.

I think #2999 is relevant when you have one c++ shared library directly linking to another c++ shared library and a pybind11 exception type crosses the abi boundary between them.  I don't think Python is really directly involved at all here.

**Comment by jbms** [comment]
Actually, I realized I hadn't looked sufficiently carefully at https://github.com/pybind/pybind11/pull/3016.  The intent of that test case indeed seems to be to allow pybind11 exceptions to be thrown by one pybind11 extension and caught/translated by another, which effectively means pybind11 abi compatibility has to also extend to the pybind11 exception types, which may not be desirable and I don't think was fully intended.

In fact there need not be any linking between the two c++ libraries, if the exception type is fully defined in a header.  Assigning non-hidden visibility to the exception type actually has two effects:

1. Allows its members to be linked globally
2. When using libc++, allows it to be globally identified for rtti purposes (I think by string comparison of their mangled names)

1 is not relevant in this case because no linking happens anyway (due to rtld_local and lack of explicit delendency from one module to the other.

2 is not relevant when using libstdc++, because it appears that types are always globally identifiable when using libstdc++ regardless of visibility.

It seems like at this point some users may be relying on the exception types as part of the abi, as in the example, and therefore the abi version must be bumped whenever their abi changes.  
This was the case even before #2999, since even without the visibility change, it worked in the common case of libstdc++.

If it is desired that the exception types not be a part of the abi, then there are some potential migration paths.

**Comment by rwgk** [comment]
To close the loop here, #4015, which triggered this PR, was closed. "Not an ABI issue" again.

I left a comment there: https://github.com/pybind/pybind11/issues/4105#issuecomment-1290050782

@jbms I think I want to use #4284 to trim back what was done with #2999. I'll tag you there when I get to it.

**Comment by rwgk** [comment]
Archiving the CI summary here before closing the PR, JIC, for future reference.

2 skipped, 54 successful, and 21 failing checks

@github-actions
Upstream / 🐍 3.11 latest internals • ubuntu-latest • x64 (pull_request) Skipped
[Details](https://github.com/pybind/pybind11/actions/runs/3318007113/jobs/5481474500)
@github-actions
CI / 🐍 3.6 • ubuntu-latest • x64 -DPYBIND11_FINDPYTHON=ON -DCMAKE_CXX_FLAGS="-D_=1" (pull_request) Successful in 12m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481474961)
@github-actions
Config / 🐍 3.7 • CMake 3.23 • ubuntu-latest (pull_request) Successful in 24s
[Details](https://github.com/pybind/pybind11/actions/runs/3318007114/jobs/5481473405)
@github-actions
Format / Format (pull_request) Successful in 55s
[Details](https://github.com/pybind/pybind11/actions/runs/3318007115/jobs/5481473629)
@github-actions
Pip / 🐍 3.6 • 📦 tests • windows-latest (pull_request) Successful in 4m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007118/jobs/5481473668)
@github-actions
CI / 🐍 3.9 • ubuntu-latest • x64 (pull_request) Successful in 13m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481475006)
@github-actions
Config / 🐍 3.7 • CMake 3.23 • macos-latest (pull_request) Successful in 1m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007114/jobs/5481473456)
@github-actions
CI / 🐍 3.10 • ubuntu-latest • x64 (pull_request) Successful in 10m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481475048)
@github-actions
Config / 🐍 3.7 • CMake 3.23 • windows-latest (pull_request) Successful in 1m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007114/jobs/5481473520)
@github-actions
CI / 🐍 3.11-dev • ubuntu-latest • x64 (pull_request) Successful in 10m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481475093)
@github-actions
Config / 🐍 3.7 • CMake 3.4 • ubuntu-latest (pull_request) Successful in 24s
[Details](https://github.com/pybind/pybind11/actions/runs/3318007114/jobs/5481473599)
@github-actions
CI / 🐍 pypy-3.7 • ubuntu-latest • x64 (pull_request) Successful in 11m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481475131)
@github-actions
Config / 🐍 3.7 • CMake 3.7 • macos-latest (pull_request) Successful in 55s
[Details](https://github.com/pybind/pybind11/actions/runs/3318007114/jobs/5481473664)
@github-actions
CI / 🐍 pypy-3.8 • ubuntu-latest • x64 -DPYBIND11_FINDPYTHON=ON (pull_request) Successful in 12m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481475183)
@github-actions
Config / 🐍 3.7 • CMake 3.18 • windows-2019 (pull_request) Successful in 2m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007114/jobs/5481473739)
@github-actions
CI / 🐍 pypy-3.9 • ubuntu-latest • x64 (pull_request) Successful in 12m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481475227)
@github-actions
CI / 🐍 3.6 • windows-2022 • x64 (pull_request) Successful in 16m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481475268)
@github-actions
CI / 🐍 3.9 • windows-2022 • x64 (pull_request) Successful in 14m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481475301)
@github-actions
CI / 🐍 3.10 • windows-2022 • x64 (pull_request) Successful in 16m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481475352)
@github-actions
CI / 🐍 3.11-dev • windows-2022 • x64 (pull_request) Successful in 14m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481475396)
@github-actions
CI / 🐍 pypy-3.7 • windows-2022 • x64 (pull_request) Successful in 19m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481475443)
@github-actions
CI / 🐍 pypy-3.8 • windows-2022 • x64 (pull_request) Successful in 18m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481475477)
@github-actions
CI / 🐍 pypy-3.9 • windows-2022 • x64 (pull_request) Successful in 18m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481475529)
@github-actions
CI / 🐍 3.6 • macos-latest • x64 (pull_request) Successful in 22m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481475560)
@github-actions
CI / 🐍 3.9 • macos-latest • x64 (pull_request) Successful in 18m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481475596)
@github-actions
CI / 🐍 3.10 • macos-latest • x64 (pull_request) Successful in 22m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481475629)
@github-actions
CI / 🐍 3.11-dev • macos-latest • x64 (pull_request) Successful in 23m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481475674)
@github-actions
CI / 🐍 pypy-3.7 • macos-latest • x64 (pull_request) Failing after 11m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481475727)
@github-actions
CI / 🐍 pypy-3.8 • macos-latest • x64 (pull_request) Failing after 8m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481475769)
@github-actions
CI / 🐍 pypy-3.9 • macos-latest • x64 (pull_request) Failing after 12m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481475812)
@github-actions
CI / 🐍 3.6 • windows-2019 • x64 -DPYBIND11_FINDPYTHON=ON (pull_request) Successful in 15m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481475858)
@github-actions
CI / 🐍 3.9 • windows-2019 • x64 (pull_request) Successful in 13m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481475897)
@github-actions
CI / 🐍 3.9-dbg (deadsnakes) • Valgrind • x64 (pull_request) Failing after 8m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481473601)
@github-actions
Format / Clang-Tidy (pull_request) Successful in 10m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007115/jobs/5481473368)
@github-actions
Pip / 🐍 3.8 • 📦 & 📦 tests • ubuntu-latest (pull_request) Successful in 1m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007118/jobs/5481473402)
@github-actions
CI / 🐍 3.11-dev (deadsnakes) • x64 (pull_request) Failing after 3m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481473680)
@github-actions
CI / 🐍 3 • Clang 3.6 • C++11 • x64 (pull_request) Failing after 2m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481472541)
@github-actions
Pip / Upload to PyPI (pull_request) Skipped
[Details](https://github.com/pybind/pybind11/actions/runs/3318007118/jobs/5481489617)
@github-actions
CI / 🐍 3 • Clang 3.7 • C++11 • x64 (pull_request) Failing after 3m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481472591)
@github-actions
CI / 🐍 3 • Clang 3.9 • C++11 • x64 (pull_request) Failing after 4m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481472641)
@github-actions
CI / 🐍 3 • Clang 7 • C++11 • x64 (pull_request) Failing after 4m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481472710)
@github-actions
CI / 🐍 3 • Clang 9 • C++11 • x64 (pull_request) Failing after 4m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481472763)
@github-actions
CI / 🐍 3 • Clang dev • C++11 • x64 (pull_request) Successful in 5m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481472821)
@github-actions
CI / 🐍 3 • Clang 5 • C++14 • x64 (pull_request) Failing after 3m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481472871)
@github-actions
CI / 🐍 3 • Clang 10 • C++20 • x64 (pull_request) Failing after 6m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481472919)
@github-actions
CI / 🐍 3 • Clang 10 • C++17 • x64 (pull_request) Failing after 4m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481472980)
@github-actions
CI / 🐍 3 • Clang 11 • C++20 • x64 (pull_request) Failing after 5m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481473032)
@github-actions
CI / 🐍 3 • Clang 12 • C++20 • x64 (pull_request) Failing after 5m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481473076)
@github-actions
CI / 🐍 3 • Clang 13 • C++20 • x64 (pull_request) Failing after 4m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481473136)
@github-actions
CI / 🐍 3 • Clang 14 • C++20 • x64 (pull_request) Failing after 5m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481473186)
@github-actions
CI / 🐍 3.10 • CUDA 11.7 • Ubuntu 22.04 (pull_request) Failing after 6m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481473906)
@github-actions
CI / 🐍 3 • CentOS7 / PGI 22.9 • x64 (pull_request) Failing after 19m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481473321)
@github-actions
CI / 🐍 3 • GCC 7 • C++11• x64 (pull_request) Successful in 4m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481474610)
@github-actions
CI / 🐍 3 • GCC 7 • C++17• x64 (pull_request) Successful in 6m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481474656)
@github-actions
CI / 🐍 3 • GCC 8 • C++14• x64 (pull_request) Successful in 4m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481474705)
@github-actions
CI / 🐍 3 • GCC 8 • C++17• x64 (pull_request) Successful in 4m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481474749)
@github-actions
CI / 🐍 3 • GCC 10 • C++17• x64 (pull_request) Successful in 4m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481474797)
@github-actions
CI / 🐍 3 • GCC 11 • C++20• x64 (pull_request) Successful in 5m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481474857)
@github-actions
CI / 🐍 3 • GCC 12 • C++20• x64 (pull_request) Successful in 5m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481474900)
@github-actions
CI / 🐍 3 • ICC latest • x64 (pull_request) Failing after 9m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481476163)
@github-actions
CI / 🐍 3 • centos:7 • x64 (pull_request) Failing after 4m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481475955)
@github-actions
CI / 🐍 3 • almalinux:8 • x64 (pull_request) Successful in 4m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481476002)
@github-actions
CI / 🐍 3 • almalinux:9 • x64 (pull_request) Successful in 4m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481476053)
@github-actions
CI / 🐍 3.7 • Debian • x86 • Install (pull_request) Successful in 3m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481476221)
@github-actions
CI / Documentation build test (pull_request) Successful in 1m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481476113)
@github-actions
CI / 🐍 3.6 • MSVC 2019 • x86 (pull_request) Successful in 6m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481476272)
@github-actions
CI / 🐍 3.7 • MSVC 2019 • x86 -DCMAKE_CXX_STANDARD=14 (pull_request) Successful in 6m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481476308)
@github-actions
CI / 🐍 3.8 • MSVC 2019 • x86 -DCMAKE_CXX_STANDARD=17 (pull_request) Successful in 5m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481476359)
@github-actions
CI / 🐍 3.9 • MSVC 2019 • x86 -DCMAKE_CXX_STANDARD=20 (pull_request) Successful in 6m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481476398)
@github-actions
CI / 🐍 3.8 • MSVC 2019 (Debug) • x86 -DCMAKE_CXX_STANDARD=17 (pull_request) Successful in 6m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481476458)
@github-actions
CI / 🐍 3.9 • MSVC 2019 (Debug) • x86 -DCMAKE_CXX_STANDARD=20 (pull_request) Successful in 7m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481476542)
@github-actions
CI / 🐍 3.9 • MSVC 2022 C++20 • x64 (pull_request) Successful in 7m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481476679)
@github-actions
CI / 🐍 3 • windows-latest • mingw64 (pull_request) Successful in 18m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481476793)
@github-actions
CI / 🐍 3 • windows-latest • mingw32 (pull_request) Successful in 19m
[Details](https://github.com/pybind/pybind11/actions/runs/3318007504/jobs/5481476899)

continuous-integration/appveyor/pr — AppVeyor build succeeded
[Details](https://ci.appveyor.com/project/wjakob/pybind11/builds/45170210)

docs/readthedocs.org:pybind11 — Read the Docs build succeeded!
[Details](https://pybind11--4283.org.readthedocs.build/en/4283/)
@pre-commit-ci
pre-commit.ci - pr — checks completed successfully

**Pull request closed without merging**
