### PR TITLE
Fix compiler error with MSVC 17 and CUDA 10.2

### PR DESCRIPTION
**Pull request by SimeonEhrig**
Fixes the compiler error described in this issue: #2180

### CODE REVIEW

**Comment by atilag** [comment]
I can confirm that solved the problem (we were facing the same exact issue).
Would love to see this merged :)

**Comment by wjakob** [comment]
I'll merge this once you've had a chance to add an extra comment. (As we do in a few other places).

Side comment: compiling pybind11 code with nvcc sounds really scary (even if it's just for the "host" part).

**Comment by SimeonEhrig** [comment]
I added the comment.

> Side comment: compiling pybind11 code with nvcc sounds really scary (even if it's just for the "host" part).

In our case, pybind11 is not the scary part to compile ;-) We use a highly [templated C++ library](https://github.com/alpaka-group/alpaka/) which also supports gcc, clang and icc as host compiler for nvcc.

**Comment by wjakob** [comment]
Thanks!

**Comment by SimeonEhrig** [comment]
> Thank you for digging into this and finding a work-around, Simeon!
> 
> I co-reported your reproducer as Nvidia Bug 3013788 so they have a chance to get their splitter/frontend into order for upcoming CUDA releases.

Thanks for reporting the bug.

**Pull request merged**
