### PR TITLE
Add note about module destructors

### LINKED ISSUE #638: Documentation: module destructor
Python supports a module destructor via `tp_dealloc`... I can't seem to figure out how to hook that in pybind11. I tried the most obvious thing I could think of (subclass module), and that doesn't work. I'm sure it's supported, right?

### PR DESCRIPTION
**Pull request by virtuald**
- Technique provided by @jagerman
- Fixes #638

### CODE REVIEW

**Comment by wjakob** [comment]
This looks good. Quick question: can't the *unused* value simply be ``nullptr``?

**Comment by jagerman** [comment]
If I recall correctly, Python won't allow a nullptr for it.  Of course, if you have some meaningful value, you should use it instead.

**Comment by dean0x7d** [comment]
Would `Py_None` work?

**Comment by virtuald** [comment]
Looking at the API docs for capsule:

* The pointer argument may not be NULL
* It's a void*, so it can be anything you want it to be

Unless someone tries to get the pointer, I don't believe the API will ever try to dereference it, so in theory you could do `Py_None` if you wanted.

**Comment by jagerman** [comment]
Instead of a static local variable, how about amending the example to:

```C++
// the capsule needs a pointer to reference; if you don't have anything better, create a simple one:
int *data = new int(123);

py::capsule cleanup(&unused, [](PyObject * capsule) {
    // do cleanup here -- this function is called with the GIL held
    int *data = PyCapsule_GetPointer(capsule, nullptr);
    delete data;
});
```

which also suggests an obvious way of how to pass data into the capsule.

**Comment by wjakob** [comment]
I was  surprised at how inelegant our way of dealing with ``py::capsule`` destructors is ;)

I submitted a separate PR to deal with this before we document the API and then can't change it anymore #752.

**Comment by wjakob** [comment]
Can you update the PR to take the future changes into account?

Thanks!

**Comment by wjakob** [comment]
closing in favor of #752

**Pull request closed without merging**
