### PR TITLE
Fix conda include reporting [do not merge]

### PR DESCRIPTION
**Pull request by henryiii**
The Conda-forge package is reporting the wrong directory. From local testing, the standard way of accessing the directory seems to be working correctly; it's just the injected special logic that is causing issues.

Is the virtualenv logic needed, or could it be removed as well?

Testing this in Conda-forge before making the PR non-draft.

### CODE REVIEW

**Comment by henryiii** [comment]
This fixed the problem with Conda here: https://github.com/conda-forge/pybind11-feedstock/pull/43

**Comment by henryiii** [comment]
The failure with CI is due to a ruby error in homebrew, and is unrelated.

**Comment by henryiii** [comment]
The thing I have not tested is that if a pip install in a conda environment works properly with this change.

**Comment by ax3l** [comment]
Thank you for the report.

As added [here](https://github.com/conda-forge/pybind11-feedstock/pull/43#issuecomment-574957768), I cannot reproduce the problem with conda (on conda-forge) that you report and this diff likely breaks the includes.

Also note that upcoming releases got again a logic change in https://github.com/pybind/pybind11/pull/1995 - maybe you are mismatching versions between development and latest stable with corresponding install logic locally?

**Comment by henryiii** [comment]
Yes, this is targeted at stable, it may be fixed in master.

**Comment by ax3l** [comment]
Got it, it's a conda-forge, Unix-only install problem.
Fix proposed in https://github.com/conda-forge/pybind11-feedstock/pull/44

**Comment by wjakob** [comment]
The logic in `__init__.py` has changed quite a bit in the meantime, and https://github.com/conda-forge/pybind11-feedstock/pull/44 landed. Can this be closed?

**Comment by henryiii** [comment]
I think so. I'll open an issue if anything is still broken.

**Pull request closed without merging**
