### PR TITLE
ci: include Boost

### PR DESCRIPTION
**Pull request by henryiii**
Add Boost to the CI checks.

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
Er, just to check, what was the motivation for this? (issue number, or Slack convo?)

I'm watching paint dry in #2376, and it seems like the Boost download can take 1m - 3m in different Mac builds:
https://github.com/pybind/pybind11/pull/2376/checks?check_run_id=985786507#step:5:9

**Comment by EricCousineau-TRI** [comment]
Ah, benchmarking, gotcha!
https://github.com/pybind/pybind11/blob/cba4a98546ed0e054fb85d1a7eb70a37154d8fd4/docs/benchmark.rst

**Comment by henryiii** [comment]
I think it also tests boost::variant (probably v1 and not v2). We might be able to cache homebrew.

**Comment by henryiii** [comment]
We can drop macOS, and leave Boost only for unix/Windows (since they don't plan to add Boost to the macOS image).

**Comment by EricCousineau-TRI** [comment]
Aye. Submitted naive PR: #2395

**Pull request merged**
