### PR TITLE
Added ability to convert from numpy.datetime64 to system_clock::time_point

### PR DESCRIPTION
**Pull request by phil-zxx**
Added ability to convert from Python `numpy.datetime64` to C++ `system_clock::time_point`

As raised here: https://github.com/pybind/pybind11/issues/2078

### CODE REVIEW

**Comment by SimonHeybrock** [comment]
Does this work with different units that `numpy.datetime64` may have, such as `datetime64[ns]`? See https://github.com/pybind/pybind11/issues/2078.

**Comment by m4ce** [comment]
any chance we could have this PR reviewed and merged? I am looking at the ability to convert chrono::system_clock::time_point to numpy.datetime64. Will this PR also work when returning a strucuted numpy array from C++ to python where a field is a time_point?

**Comment by stevesimmons** [comment]
Hi guys, is solving this on anyone's radar? I'm asking because I'd very much like the awkward-1.0#367 issue mentioned above by @jpivarski to be solved. I don't have the time right now to solve these two issues myself. Just wondering if anyone else is likely to tackle them soon...

**Comment by jpivarski** [comment]
https://github.com/scikit-hep/awkward-1.0/issues/367 for cross-linking

**Comment by SimonHeybrock** [comment]
@stevesimmons @jpivarski For `scipp`, we have since implemented bindings based on `py::array` in a manual way, supporting various time units and avoiding copies. I don't know if something like this could be brought into `pybind11` itself, but maybe this is useful for you. The two main bits are: https://github.com/scipp/scipp/blob/02aa4be8d59b84caf74d2bd37bef990e952564cf/python/bind_data_access.h#L56-L79 and https://github.com/scipp/scipp/blob/02aa4be8d59b84caf74d2bd37bef990e952564cf/python/numpy.h#L46-L63.

**Pull request closed without merging**
