### PR TITLE
chore: bump to 2.7.0

### PR DESCRIPTION
**Pull request by henryiii**

### CODE REVIEW

**Comment by joukewitteveen** [comment]
What are the consequences of this release for [the v2.7 Milestone](https://github.com/pybind/pybind11/milestone/10)? Will it be postponed to v2.8? Quite a few of the pull requests in that Milestone are somewhat old and already approved. I imagine the authors are looking forward to the merger of their code, but wouldn't be surprised if some are a bit less responsive by now.

**Comment by Skylion007** [comment]
Yeah, we plan to merge those in and are hoping to accelerate the release cycle by a quite bit.

**Comment by henryiii** [comment]
Yes, 2.7 was split into two releases, more or less. Numbers are cheap is one of my favorite sayings. :)

**Comment by henryiii** [comment]
@Skylion007 has been collecting a list of "lost" PRs to work on getting in 😄 ❤️

**Comment by henryiii** [comment]
I just moved them all to 2.8.

**Pull request merged**
