### PR TITLE
Proposed changelog for v2.2.0

### PR DESCRIPTION
**Pull request by dean0x7d**
Here is a proposed changelog for v2.2. I've tried to keep it in the same style as the previous entries. There's a pretty large number of changes, so please let me know if I've missed anything, if something needs to be reworded, or if the order of the items should change. A lot of PRs ended up in the "various improvements" item, but perhaps some of those need a full entry (or vice versa).

Unless I've missed any, the relevant PRs should all be in the [v2.2 milestone](https://github.com/pybind/pybind11/milestone/3) -- there's around a 100 PRs. I didn't check any of the out-of-PR commits.

### CODE REVIEW

**Comment by jagerman** [comment]
I think the hidden visibility change should be mentioned fairly prominently as it may potentially affect anyone not using pybind's cmake tools.

Also a suggestion for post-2.2: lets start putting changelog entries into the changelog as we merge PRs rather than waiting to the end so that all we need to do at release time is some light editing and reordering rather than writing them all up (and potentially missing things).

**Comment by dean0x7d** [comment]
> I think the hidden visibility change should be mentioned fairly prominently as it may potentially affect anyone not using pybind's cmake tools.

Good point. I'll add it.

> Also a suggestion for post-2.2: lets start putting changelog entries into the changelog as we merge PRs

Agreed.

**Comment by jagerman** [comment]
Another release-related issue: we should also update the example repositories for 2.2 (to use the `PYBIND11_MODULE` macro, but possible other things).

**Comment by wjakob** [comment]
This looks like an epic release -- sorry for not helping out more (I've been busy with other projects). In any case, I'm happy to push the button to send out the release, just let me know.

**Comment by dean0x7d** [comment]
I think the release is shaping up nicely. Maybe just one or two things to wrap up. I'll merge this changelog now so that it's accessible to PRs. Issue #953 is still open for release v2.2 in general.

**Pull request merged**
