### PR TITLE
ci: Remove "Setup Boost (macOS)" step

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Per convo: https://github.com/pybind/pybind11/pull/2393#issuecomment-674186838 - slows down the macOS builds for very little gain.

### CODE REVIEW

**Comment by henryiii** [comment]
I miss GitLab's merge when checks pass option. :'(

**Comment by EricCousineau-TRI** [comment]
Ooh, hadn't seen that in GitLab! But yeah, that would be awesome in cases like these...

**Comment by YannickJadoul** [comment]
We tried out https://github.com/apps/probot-auto-merge on `cibuildwheel`, at some point. It's ... yeah, a replacement, but there should be a better way.

**Comment by henryiii** [comment]
Did that work well enough?

**Comment by YannickJadoul** [comment]
It seems so: joerick/cibuildwheel#383 It worked, but it's maybe a bit weird to have this bot merge it, rather than it just being a feature of the platform...

**Comment by bstaletic** [comment]
https://mergify.io/ seems like an alternative to probot-auto-merge.

**Pull request merged**
