### PR TITLE
CI for smart holders as default

### PR DESCRIPTION
**Pull request by rhaschke**
This adds another CI workflow enabling `PYBIND11_USE_SMART_HOLDER_AS_DEFAULT`

### CODE REVIEW

**Comment by rhaschke** [comment]
cmake [implicitly sets `CMAKE_CXX_FLAGS="/GR /EHsc"` for MSVC](https://gitlab.kitware.com/cmake/cmake/-/issues/20610). Manually setting `CMAKE_CXX_FLAGS` overrides this default and thus requires adding those flags explicitly.

**Review by rwgk — COMMENTED** [review]
I really like that it's so easy, but I'm also really worried about introducing two copies of something so substantial. @henryiii, is there an obvious way to avoid the duplication?

Naive idea: have a small patch file somewhere else, and a bash script that applies that patch to generate this file, with a big comment at the top: "This is an auto-generated file, do not edit." And another comment with instructions how to run the bash script. — But I hope Henry knows of something more organized.

**Comment by rhaschke** [comment]
I tried to merge the new SH builds into the existing `CI` workflow before, but that ended up in a mess, because the workflow defines its jobs using matrix + includes. Doing all jobs with `PYBIND11_USE_SMART_HOLDER_AS_DEFAULT` enabled required way more changes to the `CI` workflow. With the present approach, it should be easy to keep the `CI` and `CI SH` workflow in sync.

**Comment by rwgk** [comment]
The work here was included in #2963. Closing. Thanks Robert!

**Pull request closed without merging**
