### PR TITLE
Update PGI to 20.9

### PR DESCRIPTION
**Pull request by andriish**
Update PGI to 20.9

Tag @henryiii

### CODE REVIEW

**Comment by henryiii** [comment]
The windows error is a known flake. Ignore. :)

**Comment by henryiii** [comment]
The readme number can be bumped to 20.9, as well, if you'd like.

**Comment by henryiii** [comment]
How about we leave one test (CentOS 8) with 20.7, and only bump the other? That way, the readme is truthful in saying we check both.

**Comment by henryiii** [comment]
(I can make that change if you want)

**Comment by andriish** [comment]
Hi @henryiii ,

Yes, why not.
> I can make that change if you want) 

Yes, please, I have to leave now for some hours.

Best regards,
Andrii

**Pull request merged**
