### PR TITLE
Bugfix/issue #1919 optional always move

### PR DESCRIPTION
**Pull request by fatvlady**
Added test which covers move-on-use bug for `std::optional`.
Fix is to correctly forward reference to `return_value_policy_override`.

### CODE REVIEW

**Comment by fatvlady** [comment]
Please, link to #1919

**Comment by fatvlady** [comment]
Travis problem with Pypy 2 caused by `numpy == 1.18.1` installation on build agent which requires `python >= 3.5`. Installing `numpy == 1.15.4` first and `scipy` after fixes the problem.

**Comment by m4ce** [comment]
Also came across this issue - can we get this PR merged?

**Comment by fatvlady** [comment]
@wjakob Could you please comment on this/approve? Seems like quite an easy fix with full backward compatibility.

**Comment by wjakob** [comment]
Sorry for taking a long time to look at this. One quick observation: if you study the other STL casters, you will note that they all guard the RVP override with a check of the form:
```
if (!std::is_lvalue_reference<T>::value)
```
Is there any reason for not porting that check here?

**Comment by fatvlady** [comment]
Hi @wjakob, thanks for the reply.
There's no serious reason that I can recall now. Probably my thinking was involving several points:
- `return_value_policy_override` already checks for lvalue reference, no need for duplicate logic
- I was not sure whether it is possible to have `caster<T>::cast<T&>` or vice versa, however your point re other casters implies that it is not the case in current codebase

Now, if we rely on the fact that optional dereference copies over the const-ref modifiers, most elegant solution would be to have
```
policy = return_value_policy_override<T>::policy(policy);
```
without any additional checks. Tests are passing, will commit.

**Comment by fatvlady** [comment]
^ decided to add check just to be compliant with other casters, does not change anything

**Comment by wjakob** [comment]
Ok, this is very straightforward to merge now -- thanks for making the changes.

**Pull request merged**
