### PR TITLE
Move object in pop method of List.

### PR DESCRIPTION
**Pull request by blacktea**
I suggest to move object because it should be deleted from vector, and move constructor likely faster than copy constructor.
BTW, If the class hasn't got a move constructor it would be copied.

### CODE REVIEW

**Comment by Skylion007** [comment]
@blacktea Seems like all the compilers aren't happy about this.

**Comment by blacktea** [comment]
> @blacktea Seems some of the compilers aren't happy about this.

Yep. It seems a compiler bug.
Please, look at it: https://godbolt.org/z/8ocjEzs8d
Clang 3.6 warns, Clang 3.7 is happy.
I will change using copy initialization.

**Comment by Skylion007** [comment]
Actually according to the official spec, I am pretty sure these moves are unnecessary as returned local variables are automatically moved per the specification as long as they aren't marked as const or something: https://clang.llvm.org/extra/clang-tidy/checks/performance-no-automatic-move.html , so I am not sure this PR is even necessary.

**Review by Skylion007 — APPROVED** [review]
Looks good to me, @rwgk @henryiii any objections?

**Review by rwgk — APPROVED** [review]
LGTM. Feeling good enough about it that it doesn't need the Google testing. (And it's small so easy to roll back in the unlikely event that something goes wrong.)

**Pull request merged**
