### PR TITLE
Disable builds for 3.10.0a4, and enable a nightly 3.10-dev build

### PR DESCRIPTION
**Pull request by YannickJadoul**
## Description

Temporary fix for #2774. Meanwhile, this also adds 3.10-dev nightly builds from [deadsnakes](https://github.com/deadsnakes/action).

### CODE REVIEW

**Comment by YannickJadoul** [comment]
@henryiii, this seems to be working. But I'm not sure the nightly Python versions are really worth the extra complexity (and additional almost-never-executed "Setup Python X.Y (nightly)" step). Maybe it should be a separate matrix of jobs, where we also test some debug versions? I don't know.

At any rate, feel free to push to this branch to propose changes :-)

**Comment by YannickJadoul** [comment]
> @henryiii, this seems to be working.

Neeeeeeeeevermind that. Why can't it find the correct Python? :-(

**Comment by henryiii** [comment]
I'd add a new job at least, I think.

**Comment by YannickJadoul** [comment]
Heh...

```
Run deadsnakes/action@v2.1.0
  with:
    python-version: 3.10-dev
    debug: false
```

And yet `10-dev` is still acting as if `debug` was specified. I might need to fix my own PR deadsnakes/action#18

**Comment by YannickJadoul** [comment]
Submitted a fix: deadsnakes/action#20

@henryiii, if you want to merge this before deadsnakes/action#20 would be merged, that's possible. Either as-is (with my branch, temporarily), or without the last commit (which will install the 3.10-dev debug version, but eh, should be fine).

**Comment by YannickJadoul** [comment]
> @henryiii, if you want to merge this before [deadsnakes/action#20](https://github.com/deadsnakes/action/pull/20) would be merged, that's possible. Either as-is (with my branch, temporarily), or without the last commit (which will install the 3.10-dev debug version, but eh, should be fine).

That went fast. Scratch that, the PR already got merged, and a new release released :-)

Python 2.7 doesn't work with `deadsnakes/action` (because there's no `python2.7-venv` package, and no `venv`), but ... well let's cross that bridge (and make that PR) when we need to?

**Pull request merged**
