### PR TITLE
Add note about subclasses needing virtual functions

### LINKED ISSUE #645: Wrong object type with inheritance unless virtual function is present
I'm on Fedora 24 with GCC 6.3.1, Python 3.5, haven't tested on other platforms. Here's the test code:

``` C++
#include <pybind11/pybind11.h>
#include <pybind11/functional.h>
namespace py = pybind11;


class A {
public:
    const char * whoami() { return "A"; }
};

class B : public A {
public:
    const char * whoami() { return "B"; }
    const char * b_specific() { return "I am B"; }
};

A* create_b() {
    return new B();
}

void call_with_b(std::function<void(const A&)> fn) {
    B b;
    fn(b);
}


PYBIND11_PLUGIN(python_example) {
    py::module m("python_example");
    
    m.def("create_b", &create_b);
    m.def("call_with_b", &call_with_b);
    
    py::class_<A> a(m, "A");
    a.def("whoami", &A::whoami);
    
    py::class_<B, A> b(m, "B");
    b.def("whoami", &B::whoami);
    b.def("b_specific", &B::whoami);
    
    return m.ptr();
}
```

I execute the following and get:

```
$ python3 -c 'import python_example; print(type(python_example.create_b())); python_example.call_with_b(lambda b: print(type(b)))'
<class 'python_example.A'>
<class 'python_example.A'>
```

As you can imagine, this isn't quite what I expected. I played around a bit, and I discovered that when I added a virtual function to A, then this magically started working as I expected:

``` 
$ python3 -c 'import python_example; print(type(python_example.create_b())); python_example.call_with_b(lambda b: print(type(b)))'
<class 'python_example.B'>
<class 'python_example.B'>
```

Is there something I'm missing here, or is this intended behavior?

### PR DESCRIPTION
**Pull request by virtuald**
The wording for this is terrible, but I couldn't think of a clearer way to put it. 

Fixes #645.

### CODE REVIEW

**Comment by jagerman** [comment]
I think it might make more sense to have a sort of FAQ for new-to-C++ programmers section, which would include this as one of its items.  I'm not sure whether it makes sense with just one question/answer, but perhaps there are other suitable bits of documentation that could be moved there as well?

**Comment by virtuald** [comment]
If I were searching for why my object wasn't the right type, the first section I would go to is the 'inheritance' section.

**Comment by jagerman** [comment]
I think the description could use some improvement.  You actually need more than just a virtual function: that's part of it, but you *also* need to have a virtual destructor (or be inherited from a class with one), because destruction can happen via the base class pointer.  And since a virtual destructor counts as a virtual function, typically that's all you need to worry about; other functions can be virtual as desired.

**Comment by dean0x7d** [comment]
The wording here is very confusing. It definitely needs to change. But more fundamentally, I still don't think the docs should be peppered with explanations of introductory C++ concepts ("needs at least one virtual function" is literally the definition of [a polymorphic class in C++](http://en.cppreference.com/w/cpp/language/object#Polymorphic_objects)). 

I like @jagerman's suggestion for a specific section for new-to-C++ programmers (rather than having it spread around). Perhaps this would be best if someone who went the route of Python-to-C++ could list out some of the surprises and encounters with C++'s footguns.

**Comment by virtuald** [comment]
Yes, the wording sucks, and you're right, I didn't mean polymorphic types -- I really meant subclasses. I used to use C++ extensively, but haven't needed to use it in a few years, so I've forgotten some of the finer points such as this.

Here's a rewording:

> When a wrapped function is used to return a base class pointer, that class must have at least one virtual function or the type of the object will not be inferred correctly.

At the end of the day, I don't care if it's in a FAQ or in that particular section, I would just like it to be *somewhere* so someone else doesn't spend 5 hours debugging something that they could have avoided by reading the documentation.

**Comment by jagerman** [comment]
@virtuald - I think what @dean0x7d was getting at is that it's a bit hard for us to write such a FAQ, because we write C++ day-to-day.  This point (about a virtual base) is a definite candidate for inclusion; were there other things you ran into that might be helpful, at least as a starting point?  I'm not even asking you to write them up formally, but just to let us know what you think belongs in it.

**Comment by virtuald** [comment]
I can't think of anything else at the moment. I would say that for the most part working with pybind11 has been a pleasure and far superior to other binding technologies I've used (SIP, SWIG, ctypes) in terms of ease of use, and I look forward to using it more in the future.

**Comment by dean0x7d** [comment]
I think I misunderstood the original issue here. I see now that pybind11's automatic upcasting is not actually documented anywhere. I didn't really appreciate how significant and powerful that feature really is: we don't just get access to the base interface with polymorphic behavior, we actually get the concrete instance of the derived type complete with all methods and attributes (that the base may not even be aware of). This goes beyond what C++  polymorphism usually does.

I took a stab at documenting this. It should clarify how regular and polymorphic C++ types are exported to Python. Does this look OK to everyone?

**Pull request merged**
