### PR TITLE
Remove obsolete example reference

### LINKED ISSUE #456: Link broken for "How can I reduce the build time?" in FAQ
I've dug around in the source of pybind11 to no satisfaction, but I can't find the file ``example/example.cpp`` (or what it might have been renamed to) referred to in the FAQ page.  Where did it go/ what did it become?

### PR DESCRIPTION
**Pull request by jagerman**
Fixes #456.

### CODE REVIEW

**Comment by ianhbell** [comment]
Umm...  that example isn't complete, it is not clear whether I need a ``PYBIND11_PLUGIN(example)`` wrapper block in the other files that do initialization.  A runnable(ish) example would be really nice.

**Comment by ianhbell** [comment]
I looked at the code linked in #456, and that code is clear about what needs to be done.

**Comment by dean0x7d** [comment]
Perhaps it would be clearer if the FAQ code block was split up to indicate what goes into which file? Something like:

**example.cpp**
```c++
void init_ex1(py::module &m);
void init_ex2(py::module &m);

PYBIND11_PLUGIN(example) {
    py::module m("example", "pybind example plugin");

    init_ex1(m);
    init_ex2(m);

    return m.ptr();
}
```

**ex1.cpp**
```c++
void init_ex1(py::module &m) {
    m.def("add", [](int a, int b) { return a + b; });
}
```

**ex2.cpp**
```c++
void init_ex2(py::module &m) {
    m.def("sub", [](int a, int b) { return a - b; });
}
```

**Python**
```python
>>> import example
>>> example.add(1, 2)
3
>>> example.sub(1, 1)
0
```

**Comment by ianhbell** [comment]
Yes, perfect!

**Comment by jagerman** [comment]
Good idea, updated the PR.

**Comment by wjakob** [comment]
LGTM, thanks!

**Pull request merged**
