### PR TITLE
docs: add note regarding nested type binding to "Instances and static fields" section

### PR DESCRIPTION
**Pull request by xaedes**
Add note regarding nested type binding to "Instances and static fields" section.

### CODE REVIEW

**Comment by YannickJadoul** [comment]
How, why? I don't think this is the recommended way to bind nested classes. `py::class_` takes a `scope` argument, if you want nested classes.

**Comment by YannickJadoul** [comment]
Now seeing this is related to #2032. I still don't fully understand the issue there, though, especially given the lack of formatting. Could you elaborate in which case you'd need this?

**Comment by xaedes** [comment]
Yes, good catch, I understood it wrong!
What I meant is nested type definitions like `class Foo { struct Bar { }; };`.

**Comment by YannickJadoul** [comment]
That's what I understood as well. Still not sure about #2032, though, but ... for this, the scope seems to result in the correct Python equivalent.

**Comment by xaedes** [comment]
I tried scope but that wasn't consumed by py::class_. 
I finally found how to do it (in the docs under section "Enumerations and **internal types**").
In hindsight it is obvious, instead of giving the module as first parameter to py::class_ you give it the parent class python binding:
```cpp
class Foo { struct Bar { }; };
auto foo = py::class_<Foo>(m, "Foo");
auto bar = py::class_<Foo>(foo, "Bar");
```

I still think it is too hard to find, given the amount of time I spent looking for it, but maybe I am just stupid ^^

**Comment by YannickJadoul** [comment]
@xaedes, I guess the hope is just that the signature of the constructor
```
    template <typename... Extra>
    class_(handle scope, const char *name, const Extra &... extra) {
```
would put forward the suggestion that the first argument doesn't need to be a module. But you're right that this is not really documented. The docs can always use some polishing, so if you would find a place where one or two sentences can be added (or maybe an example), that should definitely be possible to include! :-)

**Comment by xaedes** [comment]
I will draft something =)

**Comment by YannickJadoul** [comment]
Thanks! :-) Don't overdo it, I'd suggest. Just one or a few well placed sentences might give the right suggestion! :-)

**Pull request closed without merging**
