### PR TITLE
Fix so is deprecated, use ext suffix

### PR DESCRIPTION
**Pull request by MatthiasAbtIfm**
## Suggested changelog entry:

```rst

```

### CODE REVIEW

**Comment by YannickJadoul** [comment]
Do you mind filling out the template, @MatthiasAbtIfm?

**Comment by YannickJadoul** [comment]
@MatthiasAbtIfm, what going on? Not a necessary change after all?

**Comment by MatthiasAbtIfm** [comment]
sorry this wasn't supposed to go into a PR

**Comment by YannickJadoul** [comment]
Oh, right, OK. So there's nothing pybind11 should fix, then?

**Pull request closed without merging**
