### PR TITLE
Scratch PR for reducing PyPy issue observed under #4246

### PR DESCRIPTION
**Pull request by rwgk**
## Description
WIP

## Suggested changelog entry:

```rst

```

### CODE REVIEW

**Comment by rwgk** [comment]
First observation 89833837331e4bcde0302a239f1fc5889b890017: Everything works except test_gil_scoped.py

**Comment by rwgk** [comment]
Hi @mattip, after a round of brute-force-trial-and-error I'm thinking there are two problems.

1. the failed asserts you found (https://github.com/pybind/pybind11/pull/4246#issuecomment-1282378190)
2. pytest hangs in or after its tear down

We can `xfail` the 1.

But we cannot `xfail` the 2.
So I took a guess:

If you look in this PR, test_gil_scoped.py has only this left:

```
from pybind11_tests import gil_scoped as m


def test_cross_module_gil():
    """Makes sure that the GIL can be acquired by another module from a GIL-released state."""
    m.test_cross_module_gil()  # Should not raise a SIGSEGV
```

I also added some `fprintf()` to test_gil_scoped.cpp: that code block actually runs to completion (see log below).

But something in the pytest process gets upset somehow and the process hangs, I don't know for how long, I'm guessing "forever". I'll let it timeout this time; before I always cancelled manually.

Taking another guess:

I suspect there is something between

* [here](https://github.com/pybind/pybind11/blob/36ccb08b0d8f007f674ce373095b4b278689fc10/tests/test_gil_scoped.cpp#L40-L45) and
* [here](https://github.com/pybind/pybind11/blob/36ccb08b0d8f007f674ce373095b4b278689fc10/tests/cross_module_gil_utils.cpp) that upsets PyPy, and only on Windows, and only with my extra `PyGILState_Check()`s in pytypes.h

Do those two pretty small pieces of code ring any bells?

________

Copy of section in CI log:

```
============================= test session starts =============================
  platform win32 -- Python 3.9.10[pypy-7.3.9-final], pytest-7.0.0, pluggy-1.0.0
  C++ Info: MSVC 193331630 C++14 __pybind11_internals_v4_msvc_debug__
  rootdir: D:\a\pybind11\pybind11\tests, configfile: pytest.ini
  plugins: timeout-2.1.0
  timeout: 300.0s
  timeout method: thread
  timeout func_only: False
  collected 23 items
  
  test_exceptions.py .......x.........s....                                [ 95%]
  test_gil_scoped.py 
  LOOOK D:\a\pybind11\pybind11\tests\test_gil_scoped.cpp:41
  
  LOOOK D:\a\pybind11\pybind11\tests\test_gil_scoped.cpp:44
  
  LOOOK D:\a\pybind11\pybind11\tests\test_gil_scoped.cpp:48
  
  LOOOK D:\a\pybind11\pybind11\tests\test_gil_scoped.cpp:51
  
  LOOOK D:\a\pybind11\pybind11\tests\test_gil_scoped.cpp:54
  .                                                     [100%]
  
  =========================== short test summary info ===========================
  SKIPPED [1] test_exceptions.py:306: PyErr_NormalizeException Segmentation fault
  XFAIL test_exceptions.py::test_python_alreadyset_in_destructor
    Failure on PyPy 3.8 (7.3.7)
  ================== [21](https://github.com/pybind/pybind11/actions/runs/3295069314/jobs/5433235750#step:12:22) passed, 1 skipped, 1 xfailed in 1.80s ===================
```
`********` **JOB HANGS HERE FOR A LONG TIME** `********`

**Comment by rwgk** [comment]
The job was still hanging after 2h 4m. I cancelled it, getting worried about burning our CI quota for no good reason.

**Comment by mattip** [comment]
Nothing there looks familiar. To move ahead, perhaps skip the tests on windows + pypy

**Comment by rwgk** [comment]
> Nothing there looks familiar. To move ahead, perhaps skip the tests on windows + pypy

Thanks for looking again. PR #4246 already has an `#ifdef` to disable the new feature for windows + pypy, i.e. this issue is not blocking. I asked JIC a fix is easily within reach, but it's pretty clear now that's not the case. I'll add a reference to this PR to the `#ifdef`, in case someone wants to work on it later.

**Pull request closed without merging**
