### PR TITLE
travis: Ensure Python 3.8 is used, disable failing PyPy 2.7 build

### LINKED ISSUE #2159: ci: Travis Job for Python 3.8 on Linux does not actually run Python 3.8?
## Issue description

If you look at any job `Python 3.8, c++17, gcc 7 (w/o numpy/scipy)` in Travis CI builds, they don't seem to actually be using Python 3.8. (Not sure if this is due to a patch I submitted...)

Came across this is in [our fork](https://github.com/RobotLocomotion/pybind11), which effectively uses the same CI scripts here.

## Reproducible example code

See this build:

https://travis-ci.org/github/pybind/pybind11/jobs/640390164#L467
> -- Found PythonInterp: /opt/pyenv/shims/python3 (found version "3.6.7")

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #2159

Lemme know if I should take out the disabling of PyPy.

Thanks to @carlsonmark for the help!

---
This change is [Reviewable](https://reviewable.io/reviews/pybind/pybind11/2160)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
Nuts... seems like Sphinx upgrade to 3.0.0, which breaks things?

**Comment by wjakob** [comment]
Looks good, but let's definitely not drop tests if there is only a single one covering that flavor of interpreter. Can you amend this PR with the fix for Python 3.8?

**Comment by wjakob** [comment]
Hi @EricCousineau-TRI -- sorry for taking a while to respond to this PR.
First, I'd like to double-check: can this be closed now, or is it still applicable? (given that some improvements to CI have recently landed, like a38e5331d7b98f99ac4f7284ef3359b327d99241)

**Comment by EricCousineau-TRI** [comment]
Yup! I can close it!

But just to check, I looked at a few PRs, and they only had an AppVeyor status (no TravisCI status):
https://github.com/pybind/pybind11/pull/2260
https://github.com/pybind/pybind11/pull/2265

Is that expected? (and would you like that to be a separate issue?)

**Comment by wjakob** [comment]
I noticed that too. Something (not me, did not touch) recently messed up the integration. Earlier today, I removed all the permissions and recreated them. I'm hoping that bumping those PRs will fix cause all of the CI to rebuilt. Note that Travis itself is unaffected, you can log in there and see all of the builds.

**Comment by EricCousineau-TRI** [comment]
Awesome, sound great - closing now!

**Pull request closed without merging**
