### PR TITLE
Add std::valaray to docs/advanced/cast/stl.rst

### PR DESCRIPTION
**Pull request by YannickJadoul**
Cleaning up notifications, I came across this comment by @darkdragon-001: https://github.com/pybind/pybind11/pull/545#issuecomment-674075325

Bit silly in size as PR, but otherwise, we'll probably forget about it again. If necessary, I can still extend this PR by messing up some markdown and adding "an awesome project" in some places?

### CODE REVIEW

**Comment by henryiii** [comment]
I'm going to merge, partially to see if the `changelog needed` label gets added. :) I can probably set it to only care about source changes and ignore doc changes, but I want to see it work at least once first! :)

**Review by henryiii — APPROVED** [review]

**Comment by henryiii** [comment]
:tada:

**Comment by henryiii** [comment]
This line might help:
```
  - any: ['include/pybind11/**/*.h', 'tools/*.cmake*', '**/CMakeLists.txt', 'pybind11/**/*.py']
```

**Comment by YannickJadoul** [comment]
> This line might help:
> 
> ```yaml
>   - any: ['include/pybind11/**/*.h', 'tools/*.cmake*', '**/CMakeLists.txt', 'pybind11/**/*.py']
> ```

Well, better be too careful, I'd say? Looking at a PR and removing "needs changelog" is rather painless?

Anyway, great job, again! :-)

**Pull request merged**
