### PR TITLE
fix: use OVERRIDE instead of OVERLOAD

### PR DESCRIPTION
**Pull request by henryiii**
@YannickJadoul, I undid a few changes from #2325 in #2478 due to a bad rebase (I had the change backwards for some reason). This should fix it, I think.

### CODE REVIEW

**Review by YannickJadoul — APPROVED** [review]
Looks good to me! :-)

**Comment by henryiii** [comment]
Okay, one of us can merge when tests pass. ;)

**Comment by YannickJadoul** [comment]
Thanks for the docs fix!

**Comment by NickAlger** [comment]
FYI, the default version installed using conda still uses OVERLOAD. At present, anyone who installs pybind11 via conda will get an error when they try to follow this tutorial (this happened to me, leading to several hours of confusion before I found this thread)

**Comment by YannickJadoul** [comment]
@NickAlger, what's the version you get from conda, then?

**Comment by YannickJadoul** [comment]
@NickAlger, I downloaded a random package from [here](https://anaconda.org/conda-forge/pybind11/files), and it does contain the correct 2.6.0 files. Now I'm very curious where you got your version.

**Comment by NickAlger** [comment]
@YannickJadoul Looks like 2.4.3, installed 3 days ago via 
conda install -c conda-forge pybind11
But looking into it further, it seems like conda decided to install version 2.4.3 for compatibility with some other package in the environment (fenics). Using a new conda environment installs 2.6.0

**Comment by YannickJadoul** [comment]
@NickAlger, that's quite horrible; quite a few things have been improved since 2.4.3. Anyway, thanks for looking into that! :-)

**Pull request merged**
