### PR TITLE
Some fixes

### PR DESCRIPTION
**Pull request by cyyever**
Fix some code problems found by PVS-Studio  and clang-tidy analyzers.

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Comment by rwgk** [comment]
Hi @cyyever, LGTM and I want to merge this asap (based on @Skylion007's approval and my own), but could you please add a hint to the PR description why you applied this fix? Did some tool find it (like clang-tidy)? Sanitizer? Or just something you noticed? (All of these are good reasons IMO.)

**Comment by rwgk** [comment]
BTW: The CI failure is a flake that I've seen several times before and we can safely ignore.

**Comment by cyyever** [comment]
@Skylion007  @rwgk  I have committed some more changes.  Most of the tests run successfully, but please review the code.

**Comment by rwgk** [comment]
Before we look at the details, could you please explain why you started working on the changes, and how you picked out the places you changed?

**Comment by rwgk** [comment]
FWIW: The CI failures are unrelated flakes I've seen several times before.

**Comment by cyyever** [comment]
@rwgk  In order to achieve better code quality, I used various coda analyzers to scan the source code and checked each warning.

**Comment by rwgk** [comment]
> @rwgk In order to achieve better code quality, I used various coda analyzers to scan the source code and checked each warning. The used tools were mentioned above. Also because pytorch and some other projects use pybind and I need to make sure pybind being as stable as possible

That sounds good. I'm glad they didn't find more! Could you please summarize in the description what those analyzers were, ideally with version numbers? That way we can reason about the changes in the future. Also, what do you think how feasible it is to integrate them into GitHub actions, so that we stay healthy in the future. (That would be separate PRs.)

**Comment by Skylion007** [comment]
@rwgk Looks like the Clang-Tidy check I was going to turn on, cppcoreguidelines-init-variables, . Not sure about that last diff though.

**Pull request closed without merging**
