### PR TITLE
check for already existing enum value added; added test

### PR DESCRIPTION
**Pull request by cysiek**
Fix for https://github.com/pybind/pybind11/issues/1451 (Defining enum with mutiple identical values should cause an error)
Now trying to add already existing value throws an exception.

### CODE REVIEW

**Comment by bstaletic** [comment]
That error on Travis is definitely unrelated to your changes.

As for your PR, it looks good. I personally like `pyname` more than `name_converted`, but that's a matter of taste.

**Comment by bstaletic** [comment]
I can't say anything about this getting merged because I don't have write access to the repo.
The travis fix is in #1454.

**Comment by cysiek** [comment]
So... now this pull request will be accepted? Or something is missing?

**Comment by wjakob** [comment]
Merged, thank you!

**Pull request merged**
