### PR TITLE
Use correct itemsize when constructing a numpy dtype from a buffer_info

### PR DESCRIPTION
**Pull request by patstew**
As requested by @aldanor in #488

### CODE REVIEW

**Comment by wjakob** [comment]
@aldanor, could you please take a look and approve the specific change & test?

**Comment by aldanor** [comment]
As I said in the other PR, this looks good to me, thanks @patstew. The added test also fails without this fix on the latest master.

// The whole dtype vs format string thing is mildly clunky/convoluted but maybe we can refactor it later (not our fault that numpy does it wrong...)

**Comment by wjakob** [comment]
Merged (with spacing fix)

**Comment by wjakob** [comment]
Congratulations, that was commit 1000 🎉  ;)

**Pull request closed without merging**
