### PR TITLE
fix(cmake): add required emscripten flags

### PR DESCRIPTION
**Pull request by henryiii**
## Description

Putting this in for our next release. The Pyodide authors thought this was a good idea in their Discord a while back.

## Suggested changelog entry:

```rst
* When compiling for WebAssembly, add the required exception flags (CMake 3.13+)
```

CC @hoodmane, @agriyakhetarpal

### CODE REVIEW

**Review by rwgk — APPROVED** [review]
SGTM although I can really only contribute a question:

How/why did the workflow here pass before `-fexceptions` was added?

Asking the same question from a different angle: What is fixed by adding the option? (Is that not tested here?)

It would be great if you could add a sentence or two to the PR description, to answer that question.

**Review by agriyakhetarpal — APPROVED** [review]
Thanks, @henryiii! Please note the typo in the suggested CHANGELOG entry ("requried" ➡️ "required").

**Comment by henryiii** [comment]
> How/why did the workflow here pass before -fexceptions was added?

I forgot to remove it from the CI, it was manually added (done now).

I believe pybind11 always requires exception handling enabled?

**Comment by henryiii** [comment]
And you can now see what happens if the flag is missing in the CI history. We are going to pretend I intended to do that. :)

**Comment by rwgk** [comment]
> And you can now see what happens if the flag is missing in the CI history. We are going to pretend I intended to do that. :)

Is this what you expected?

* https://github.com/pybind/pybind11/actions/runs/10353001156/job/28654855427?pr=5298

```
  ../../../../home/runner/work/pybind11/pybind11/tests/test_buffers.py ... [  0%]
  .............Pyodide has suffered a fatal error. Please report this to the Pyodide maintainers.
```

I think I understand now why it worked before (d61a69b37f54cee4a5aa39ab5e1c057045ab4bd6), but TBH I don't understand why the current state of this PR produces that error.

(Google has a general ban on C++ EH, with an exception for pybind11. Of course, mixups happen, and when we accidentally tried to compile pybind11 header without C++ EH enabled, we got build errors, not runtime errors.)

> I believe pybind11 always requires exception handling enabled?

Yes. (Even pybind11/pytypes.h, although that almost works without C++ EH. Making that optional would be a great thing for Google, but I never got to that.)

**Review by rwgk — APPROVED** [review]

**Comment by hoodmane** [comment]
Thanks @henryiii1

**Comment by QuLogic** [comment]
IIUC, this only gets added to CMake, but not `pybind11-config`, so this gets missed out on packages that use, e.g., Meson to build. Since Meson has [its own custom pybind11 lookup](https://github.com/mesonbuild/meson/blob/master/mesonbuild/dependencies/python.py#L48-L63)  (all it does it call `pybind11-config --includes`), do you think something should be added there, it should change to use the CMake files somehow, or should `pybind11-config` gain some `--c(xx)flags`-type flag to output stuff like this for non-CMake use?

**Comment by henryiii** [comment]
This would have to be cross-compilation aware. `pybind11-config` can't know you are cross-compiling to Emscripten?

**Comment by QuLogic** [comment]
Ah, I suppose so then. It could get a `--target` flag, perhaps, but then there'd have to be all that logic repeated in the script. So do you think it makes more sense to place in Meson instead?

**Comment by henryiii** [comment]
@eli-schwartz Thoughts? Happy to add whatever we need here.

**Pull request merged**
