### PR TITLE
fix: make PYBIND11_WARNING_POP actually pop clang diagnostics

### PR DESCRIPTION
**Pull request by J-M0**
## Description

`PYBIND11_WARNING_POP` is defined for clang as `PYBIND11_PRAGMA(clang diagnostic push)`, meaning ignored diagnostics don't actually get reset.

## Suggested changelog entry:

```rst
``PYBIND11_WARNING_POP`` was incorrectly defined as ``PYBIND11_PRAGMA(clang diagnostic push)``
```

### CODE REVIEW

**Comment by J-M0** [comment]
I'm not sure if this is the right solution, but it's the best result I've gotten so far

**Comment by J-M0** [comment]
To expand a little more, until C++20, the standard required that at least one value be given for the `...` in a variadic macro. The problem here is twofold:

1. On C++20 and up, clang still wrongly flags empty `__VA_ARGS__` as an extension.  
https://github.com/llvm/llvm-project/issues/76375

2. For older C++ versions, `-Wno-gnu-zero-variadic-macro-arguments` needs to be set *before* calling a variadic macro with zero variadic arguments. Disabling the warning can't be baked into the macro definition as far as I can tell. There are a lot of places where pybind11 uses empty `__VA_ARGS__`, so that's why I opted to ignore it globally in CMakeLists.txt. I'm worried though that this doesn't actually fix the problem for downstream pybind11 users.

**Comment by rwgk** [comment]
Oh sorry, what I had in mind is changing the C++ code to conditionally use the C++20 feature. (No cmake changes.)

I'll give it a try.

**Comment by rwgk** [comment]
My idea that `__VA_OPT__(,) __VA_ARGS__` could help only made the problem worse. However, while going down that rabbit hole I discovered that

* the warnings related to the `PYBIND11_OVERRIDE` family of macros disappear with clang 14 or newer,

* but the same warning is still generated for `PYBIND11_DECLARE_HOLDER_TYPE` even with clang18.

To  get around both problems, I believe it's a useful compromise to

* add a sticky (i.e. no push/pop) warning suppression in pybind11/pybind11.h **for clang < 14 only**, and

* make a small change to the `PYBIND11_DECLARE_HOLDER_TYPE` macro in pybind11/cast.h to side-step the same warning there.

**Comment by J-M0** [comment]
Yeah I ran into those same problems too, but I see I didn't articulate that well. I did try to ignore the warning globally by adding it to `PYBIND11_NAMESPACE_BEGIN()` but that still had errors since the warning got popped.

So how do we want to go from here? Squash this PR down to two commits?

**Comment by rwgk** [comment]
> Yeah I ran into those same problems too, but I see I didn't articulate that well. I did try to ignore the warning globally by adding it to `PYBIND11_NAMESPACE_BEGIN()` but that still had errors since the warning got popped.
> 
> So how do we want to go from here? Squash this PR down to two commits?

We always use Squash and merge.

While working on a PR, I find it very useful to never force push, and to leave a comment with each commit to explain the next step. That way it's easy for others to follow the progress, and also easier to backtrack.

I posted a review request in a chat room where other maintainers hang out. I'll wait a few days to see if anyone sends feedback.

**Review by rwgk — APPROVED** [review]
There was no feedback for anyone else for a week.

Thanks again for the fix!

**Pull request merged**
