### PR TITLE
doc: Add "Getting Help" section

### LINKED ISSUE #1724: doc: Make Gitter + StackOverflow links more prominent?
I've seen quite a few issues that aren't really bug reports or feature requests; the issues templates does direct people to use Gitter, but it seems that there are still quite a few issues that get by.

Would it help to make a "Getting Help" section in the RTD docs, perhaps right under "About this project", to point to Gitter / StackOverflow?

(I'm posting this assuming that this is not a huge issue, but perhaps could still be optimized. If this is a complete non-issue, feel free to close this!)

### PR DESCRIPTION
**Pull request by eacousineau**
Resolves #1724 (if it helps)

Modeling this after what we did on Drake: https://drake.mit.edu/getting_help.html

Meta:
~Is there an easy way to search Gitter chatrooms? I've struggled to figure this out, and it seems like a *really* rich source of info if it were easily searchable...~ See response below.

### CODE REVIEW

**Comment by bstaletic** [comment]
> Is there an easy way to search Gitter chatrooms? I've struggled to figure this out, and it seems like a really rich source of info if it were easily searchable...

In the upper left corner there are, in order, downwards, Gitter logo, "All conversations" and finally "Search Gitter".

**Comment by eacousineau** [comment]
Ah, sweet, thanks! I had seen that before, but I thought that search all of Gitter, because the ordering of results are first "Rooms & People", then "Chat Messages"; however, searching as you mentioned, the posts do appear to be constrained to `pybind11/Lobby`.
(I do kinda wish that they had a better search interface though...)

**Comment by wjakob** [comment]
Hi Eric,

this is generally a good idea, but I'd like to include as much as possible of this information in the ISSUE_TEMPLATE.md — I want people to be forced to read that rather than having just a single line that is quick to delete.

This project has become very popular and is getting seriously hammered with issue reports (328 and counting!). Part of the reason is that many people fire off tickets for "obvious" questions without reading the manual.

Best,
Wenzel

**Comment by eacousineau** [comment]
Sounds good! If possible, it'd be great to see a StackOverflow link, and maybe a quick tip on searching for Gitter (given that I, uh, struggled with the obvious :P) on the issue template.

I'll go ahead and close this PR, and try that out.

**Pull request closed without merging**
