### PR TITLE
pybind11.setuptools.Extension for simpler builds.

### PR DESCRIPTION
**Pull request by anntzer**
Allows building with a simple setup.py:

    from pybind11.setuptools import Extension

    setup(ext_modules=[Extension("module.name", ["module/name.cpp"])])

Mostly copy-pasted from pybind11/pybind_example.

See #348.

### CODE REVIEW

**Comment by wjakob** [comment]
cc @SylvainCorlay

**Comment by SylvainCorlay** [comment]
Do you think that we have polished this enough that it can be abstracted out?

**Comment by wjakob** [comment]
Agreed, it would be nice if there was a way to benefit from the shorter notation while still being able to specify compiler/linker flags & include paths.

**Comment by anntzer** [comment]
You can pass kwargs (including more include dirs and compiler flags) as usual to the Extension class, the new ctor simply appends the relevant include dirs and compiler flags.
Admittedly it should probably append the include dirs but *prepend* the compiler flags (to make both overridable).

**Comment by wjakob** [comment]
One issue that I see is the behavior when pybind11 isn't yet installed. The current setuptools approach still works, i.e. it will install pybind11 and then continue as usual. It seems like the proposed change will break this behavior.

**Comment by anntzer** [comment]
I tried to hack something using setup_requires, but didn't get anywhere.
On the other hand this same issue has been plaguing numpy and cython for a while too...

The current approach requires copy-pasting a large chunk of code to `setup.py`, which isn't very appetizing either.

**Comment by SylvainCorlay** [comment]
> One issue that I see is the behavior when pybind11 isn't yet installed. The current setuptools approach still works, i.e. it will install pybind11 and then continue as usual. It seems like the proposed change will break this behavior.

On this regard I think that the us of a get `get_include` is finally not a very good idea. We go through contorsions to delay the evaluation to after the time when it is installed while the content of the function only does  `return locations.distutils_scheme('pybind11')['headers']`.

Overall I am 👎 on this since it hides more of logic that should be in setup.py to be tweaked for each specific downstream project, which will now require various hooks to customize (over-engineering).

**Comment by anntzer** [comment]
To be honest I don't really understand the criticism.

On the issue of the dependency on pybind11:

Either one wants to write a `setup.py` that will work even if pybind11 is not installed yet (in which case you need to go through the contorsions mentioned by @SylvainCorlay) or one accepts that similarly to numpy and cython, a dependency on pybind11 can only be *documented*, not programmatically written in the `setup.py`.  I have chosen to follow the second option, and thus don't need to do anything fancy to delay the call to `get_include`.  Of course, nothing prevents you from sticking to @SylvainCorlay's `setup.py`.

On the issue of "hiding logic":

AFAICT any extension module that relies on pybind11 (and setuptools) needs to pass some options to the Extension class: `language` must be set to `"c++"`, `include_dirs` needs to include the pybind11 include directories, and a c++11 or c++14 compatibility flag to the C compiler.  Additionally, it is recommanded to set the default visibility of symbols to hidden.  These are the *only* things this PR does (modulo a few platform-specific things (`/EHsc` on Windows, etc.) I copy-pasted from @SylvainCorlay's example, but I don't really know anything about compilation options on Mac or Windows, so if they are irrelevant I can strip them out too); in other words, I expect any project that relies on setuptools and pybind11 to have to need some similar code (but please let me know if I am wrong).

Note that *no additional hooks* are provided: the Extension class still provides the same interface as the normal `setuptools.Extension`, and it is trivially possible to override the defaults provided by `pybind11.setuptools.Extension` by adding more include dirs (which go in front of the defaults), more compilation flags (which go after the defaults), or simply using sticking to `setuptools.Extension` instead of `pybind11.setuptools.Extension`.

**Comment by SylvainCorlay** [comment]
> Either one wants to write a setup.py that will work even if pybind11 is not installed yet (in which case you need to go through the contorsions mentioned by @SylvainCorlay) or one accepts that similarly to numpy and cython, a dependency on pybind11 can only be documented, not programmatically written in the setup.py. I have chosen to follow the second option, and thus don't need to do anything fancy to delay the call to get_include. Of course, nothing prevents you from sticking to @SylvainCorlay's setup.py.

We don't have to go through this contorsions. We could drop `get_include` and use `locations.distutils_scheme('pybind11')['headers']`.

**Comment by anntzer** [comment]
>> Either one wants to write a setup.py that will work even if pybind11 is not installed yet (in which case you need to go through the contorsions mentioned by @SylvainCorlay) or one accepts that similarly to numpy and cython, a dependency on pybind11 can only be documented, not programmatically written in the setup.py. I have chosen to follow the second option, and thus don't need to do anything fancy to delay the call to get_include. Of course, nothing prevents you from sticking to @SylvainCorlay's setup.py.

> We don't have to go through this contorsions. We could drop get_include and use locations.distutils_scheme('pybind11')['headers'].

Which is fine, we can use that instead in `pybind11.setuptools.Extension` too.
From my experience, projects that are based on numpy or cython have accepted this limitation for a long time.

>> Note that no additional hooks are provided: the Extension class still provides the same interface as the normal setuptools.Extension, and it is trivially possible to override the defaults provided by pybind11.setuptools.Extension by adding more include dirs (which go in front of the defaults), more compilation flags (which go after the defaults), or simply using sticking to setuptools.Extension instead of pybind11.setuptools.Extension.

> You may have other compilation options, include directories, binary directories. Pretty much everything here is changeable for good reasons.

... then just add them as additional kwargs to `Extension`?  Again: if it is (sanely) possible to use pybind11 without the flags that this PR provides by default, please let me know.  But as far as I can tell, this simply provides a standard, necessary base (*for projects that rely on setuptools*), upon which you can add whatever you want.

**Comment by SylvainCorlay** [comment]
On Tue, Aug 23, 2016 at 10:09 AM, Antony Lee <notifications@github.com>
 wrote:
>
> From my experience, projects that are based on numpy or cython have
> accepted this limitation for a long time.
>
I had some discussions with numpy core devs at scipy 2016 on adopting the
install_headers approach. I think that this situation is terrible,
especially since there is absolutely no reason for it to be the case.

On Tue, Aug 23, 2016 at 10:09 AM, Antony Lee <notifications@github.com>
wrote:
>
> ... then just add them as additional kwargs to Extension? Again: if it is
> (sanely) possible to use pybind11 without the flags that this PR provides
> by default, please let me know. But as far as I can tell, this simply
> provides a standard, necessary base (*for projects that rely on
> setuptools*), upon which you can add whatever you want.
>
The fact that it is semi-boilerplate is the reason why I started the
example project in the first place. Although for things that have an API
surface almost larger than the actual implementation, new layers tend to
complicate things more than they help.

**Comment by anntzer** [comment]
>> From my experience, projects that are based on numpy or cython have
 accepted this limitation for a long time.

> I had some discussions with numpy core devs at scipy 2016 on adopting the
install_headers approach. I think that this situation is terrible,
especially since there is absolutely no reason for it to be the case.

Can you tell me more about this approach?  I have never heard of it.

>> ... then just add them as additional kwargs to Extension? Again: if it is
 (sanely) possible to use pybind11 without the flags that this PR provides
 by default, please let me know. But as far as I can tell, this simply
 provides a standard, necessary base (*for projects that rely on
 setuptools*), upon which you can add whatever you want.

> The fact that it is semi-boilerplate is the reason why I started the
example project in the first place. Although for things that have an API
surface almost larger than the actual implementation, new layers tend to
complicate things more than they help. (get_include is a good example of that!)

I feel like we're talking past each other right now.  The API surface of my proposal is exactly one class, with the same documented interface as `setuptools.Extension`.  The implementation is not trivial due to the need to support multiple platforms and compilers.

Let's look at it from the point of view of the end user (developer), who chooses to use `pybind11.setuptools.Extension`, and accepts to have a documented dependency on pybind11 (which may not be too bad as he may already have a documented dependency on numpy, for example) (e.g.: myself): he gets to save the need to pass a few options, that may well only arise from the use of pybind11 and be otherwise irrelevant for him, to the Extension class; additionally these options may be tricky to get right in a cross-platform context.

**Comment by SylvainCorlay** [comment]
> > > From my experience, projects that are based on numpy or cython have
accepted this limitation for a long time.

> > I had some discussions with numpy core devs at scipy 2016 on adopting the
install_headers approach. I think that this situation is terrible,
especially since there is absolutely no reason for it to be the case.

> Can you tell me more about this approach? I have never heard of it.

The idea is the add a `headers` kwargs in numpy's setup.py so that headers of numpy are installed in the standard location under sys-prefix instead it being package data like right now. 

The benefit is that get_include will not be required anymore (and you will not need numpy anymore in your setup.py), since you will be able to do `locations.distutils_scheme('numpy')['headers']`.

**Comment by anntzer** [comment]
Fair enough (and an idea I like).  I would consider that the benefits of my proposal still stay valid though.

**Comment by wjakob** [comment]
If the ``install.py`` script just fails when pybind11 is not installed, it's an absolute no-go for me. I'll close this for now, but I am happy to reopen the PR if a better solution can be found.

**Pull request closed without merging**
