### PR TITLE
cmake: Expose `PYBIND11_TEST_OVERRIDE`

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Primarily for the ccmake curses GUI

I've found myself using this quite a bit, and would love to have it a bit more accessible.

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
@rwgk I'm not sure if it would make sense, as `set(... CACHE ...)` / `option(...)` cache vars are pretty standard for CMake configuration.
https://cmake.org/cmake/help/latest/command/set.html#set-cache-entry
https://cmake.org/cmake/help/latest/command/option.html

@jamiesnape If you have time, can I ask your opinion (on the CMake side)?

**Comment by jamiesnape** [comment]
I do not think the CMake constructs need documenting, but the docstring in the `set(... CACHE)` could be improved, I think. Override tests is a little vague. Something like "tests from ;-separated list of *.cpp files will be built instead of all tests"?

**Comment by EricCousineau-TRI** [comment]
Done - thanks!

**Comment by wjakob** [comment]
LGTM, thanks!

**Pull request merged**
