### PR TITLE
refactor: drop mkdoc and update changelog

### LINKED ISSUE #1831: tools/clang using relative submodule breaks non-github superprojects
https://github.com/pybind/pybind11/blob/502ffe50a9f22c04637bbc8ec0019488458ba948/.gitmodules#L3

Using a relative path here breaks cases where pybind11 is itself used as a submodule in another repo _that is not hosted on github_.

The issue is raised when doing a recursive submodule update on the super project, as relative paths are resolved based on the superprojects URL (and there is no way that I know of to exclude a single submodule from the recursive update, since command line options override settings from .gitmodules).

Since you use this as an internal tool (#807), would you consider changing back to an absolute url, such as `git@github.com:wjakob/clang-cindex-python3.git`, or perhaps removing the submodule?

### PR DESCRIPTION
**Pull request by henryiii**
This adds a pointer to the new repo and drops the old submodule. If this is
renamed `pybind11-mkdoc` -> `pybind11_mkdoc`, this can easily be updated before
merging.

Also updates the changelog. PR authors are welcome to update / fill in / add!
Includes #2489, as it should be going in in the near future.

Follows #2482, closes #1831, closes #1872.

### CODE REVIEW

**Review by bstaletic — APPROVED** [review]
Clean up with ~400 lines removed. What's not to like?

**Comment by wjakob** [comment]
This is probably slightly annoying to do, but would you mind re-basing your changes in `https://github.com/pybind/pybind11-mkdoc` in a way that keeps the history of the main `mkdocs` file in this repository? Others contributed to this over time, and it would be nice to retain the record of that. (Something like what's described here https://stackoverflow.com/questions/7375528/how-to-extract-one-file-with-commit-history-from-a-git-repo-with-index-filter).

**Comment by wjakob** [comment]
Other than that, this all looks great, and thank you for adding the changelog!

**Review by wjakob — APPROVED** [review]

**Comment by henryiii** [comment]
Yes, I didn't think about that, but I could do that. Are you interested in moving `pybind11-mkdoc` to `pybind11_mkdoc` for consistency?

**Comment by henryiii** [comment]
Okay, rebased into `pybind11_mkdoc`. Putting this in, then.

**Pull request merged**
