### PR TITLE
Add clang15 C++20 job

### PR DESCRIPTION
**Pull request by rwgk**
## Description
Just keeping up.

## Suggested changelog entry:

```rst

```

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Review by henryiii — APPROVED** [review]
IMO, we don't need all the in-between jobs - just the first and last compiler for each C++ mode would be fine. Also, I think all the tags (at least the maintained ones) now have the -bullseye suffix.

**Comment by rwgk** [comment]
What are the pros-and-cons for omitting some clang versions?

Pros:
* Reduce carbon footprint.

I cannot think of anything else: the CI will not finish any faster, it doesn't cost us anything, the resources are paid for already.

Cons:
* General: if it's not tested, it might be broken. No compiler is bug free.
* When figuring out compiler-specific `ifdef`s we don't have all the data we need. (I was in that situation several times.)
* When experimenting with what compiler supports a certain C++ feature, we don't have all the data we need.
* If/when we want to do performance analyses, we don't have all the data we need.
* Deciding what versions to cover requires human cycles (guesswork), as for example right now. We could do something else with our time.

**Comment by Skylion007** [comment]
Yeah, feel free to have all the clang-versions. I think we just might want to add bullseye to some other containers so it uses the latest version :P

**Comment by rwgk** [comment]
The CI after merging this PR had 6 failures, all seem ubuntu related, apt-get failures. Does someone know already what we need to do to get back to normal?

**Comment by Skylion007** [comment]
Not seeing any failure?

**Comment by rwgk** [comment]
Apparently @henryiii triggered a rerun, and then all failed jobs succeeded:

1. https://github.com/pybind/pybind11/actions/runs/3907641043/attempts/1
2. https://github.com/pybind/pybind11/actions/runs/3907641043

Nice! Back to normal with a couple clicks.

**Pull request merged**
