### PR TITLE
Replace error printing code gated by NDEBUG with a new flag: PYBIND11_DETAILED_ERROR_MESSAGES 

### PR DESCRIPTION
**Pull request by voznesenskym**
## Description

Does what it says in the title. We have some internal use cases of pybind where we would love to get richer logging from within pybind, but are not running a debug build.

### CODE REVIEW

**Comment by voznesenskym** [comment]
Apologies upfront if this is not desired. I am not 100% sure how to test it, I did run all unit tests and nothing exploded.

**Review by Skylion007 — APPROVED** [review]

**Comment by voznesenskym** [comment]
> Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.

@Skylion007 Thanks for the stamp, I do not have merge access :)

**Comment by Skylion007** [comment]
Any objections @henryiii or @rwgk ? If not, let's merge it.

**Comment by voznesenskym** [comment]
@rwgk thanks for the great feedback. Applied.

w/r/t

> Optional, or follow-on PR: define the macro for at least one non-debug CI job (very easy) and verify that some error is complete with details (needs some thought, unless someone already has a good idea how to implement that).


There are tests in `tests/test_methods_and_attributes.py` and `tests/test_pytypes.py` that test that the correct mode prints the correct value. It's not perfect, as it relies on `debug_enabled` being set, which is set from reading the right #define, but can of course be set by anyone, anywhere.

**Review by rwgk — APPROVED** [review]
Looks great to me!

@Skylion007, do you want to take another look?

**Review by Skylion007 — APPROVED** [review]

**Pull request merged**
