### PR TITLE
Missing CMakelist in source tarball

### PR DESCRIPTION
**Pull request by SylvainCorlay**
Another possibility is to have conda-forge fetch the tarball from GH.

@wjakob thoughts?

### CODE REVIEW

**Comment by wjakob** [comment]
Can you explain the context of these two PRs in more detail? I looked at both and quite frankly don't understand. (For instance, "just" the top level CMakeLists.txt is not enough to do anything, since it includes ``pybind11Tools``, etc.)

**Comment by wjakob** [comment]
Why are there two PRs, and how are they related? What is this trying to accomplish?

**Comment by SylvainCorlay** [comment]
The goal of the other PR is to implement what was described in https://github.com/pybind/pybind11/pull/652 i.e. enable the inclusion of the `pybind11Config.cmake` files  in the conda package.

**Comment by SylvainCorlay** [comment]
But

**Comment by SylvainCorlay** [comment]
I have updated the other PR for it to fetch the tarball from GH archives, and unlike the pypi tarball, it has everything.

**Comment by wjakob** [comment]
ok, sounds good!

**Pull request closed without merging**
