### PR TITLE
Install headers using both headers and package_data

### PR DESCRIPTION
**Pull request by isuruf**
Fixes https://github.com/pybind/pybind11/issues/1067
Fixes https://github.com/pybind/python_example/issues/45

### CODE REVIEW

**Comment by wjakob** [comment]
This commit will break virtually every project that recursively includes pybind11 as a git submodule because you are changing the location of the header files. That's really a no-go for me.

**Comment by isuruf** [comment]
@wjakob, it turns out that changing the location is not needed. This is now backwards compatible.

**Comment by isuruf** [comment]
With this PR, pybind11 doesn't have to be installed before installing the downstream package and downstream packages need `pybind11` only in `setup_requires`. See https://github.com/pybind/python_example/pull/47

**Comment by wjakob** [comment]
cc @sdebionne, @ax3l 
This PR removes some of the Conda-specific changes made as part of #1877. Would you mind taking a look?

**Comment by ax3l** [comment]
Thanks for the ping. I'll try this with [spack](https://github.com/spack/spack/) as well after lunch.

**Comment by ax3l** [comment]
Hm, I do not thing the new implementation helps much if we are in CMake-controlled/`PYBIND11_USE_CMAKE` installation mode... but otherwise okay for me if it helps with `setup.py`-based installs.

**Comment by isuruf** [comment]
Even in `PYBIND11_USE_CMAKE` mode, the headers are installed in `site-packages/pybind11/include` inside the python installation, which duplicates the headers, but that's a small price to pay IMO to allow the different use-cases namely, cmake installs, pip installs, pep517 installs, submodules.

**Comment by ax3l** [comment]
Okay, sounds good to me.
I actually meant CMake-only mode. But I can use the `USE_PYTHON_INCLUDE_DIR` option for that, too.

**Comment by wjakob** [comment]
@isuruf : I'll go ahead and merge this then, or did you plan to make additional changes?

**Comment by isuruf** [comment]
No. This is ready from my end.

**Comment by wjakob** [comment]
Ok -- merged!

**Comment by marscher** [comment]
Many thanks to all contributes/reviewers to fix this long outstanding issue! :+1:

**Comment by SylvainCorlay** [comment]
pep517 is causing so much breakage, especially with the user isolation...

**Comment by ax3l** [comment]
But the `pyproject.toml` is so nice :)
Ok, enough spamming...

**Comment by isuruf** [comment]
@wjakob, any plans for a new release using this?

**Comment by xunkai55** [comment]
+1 for the release. It would help a lot :-)

**Comment by wjakob** [comment]
FYI: I've finally release v2.5.0, which includes this fix.

**Pull request merged**
