### PR TITLE
[Minor] Fixing typo in docs

### PR DESCRIPTION
**Pull request by philbucher**
## Description
Fixing a typo in the docs

## Suggested changelog entry:
None

### CODE REVIEW

**Review by henryiii — APPROVED** [review]

**Comment by henryiii** [comment]
I've cherry-picked this to master, will likely make a mess when we merge, but hopefully it will at least not be wiped out.

**Comment by philbucher** [comment]
my apologies :/

I am not sure why it targeted `stable` as target branch, as you seem to be using `master` as default branch

in any case, having it in the description of the PR template will help! => #3313

**Comment by henryiii** [comment]
You probably clicked "edit this page" on the docs, which technically is from stable (the stable docs are the default, though both are rendered). So not sure if, following this path, users will be aware that they are targeting `stable` in order to follow #3313, but it's at least worth adding.

**Comment by philbucher** [comment]
yes exactly thats what I did

I think with the hint you added it should be possible to notice in time and switch the target branch before opening the PR

**Pull request merged**
