### PR TITLE
Add short description and link to Scapix

### PR DESCRIPTION
**Pull request by Boris-Rasin**

### CODE REVIEW

**Comment by wjakob** [comment]
This looks like a nice and useful project. However, endorsing a commercial product directly from the pybind11 documentation is out of the question.

**Comment by Boris-Rasin** [comment]
What's a "commercial product"?

**Comment by wjakob** [comment]
I would want linked projects to follow a reasonable open source license, e.g. one of the OSI-approved ones. (https://opensource.org/licenses)

**Comment by Boris-Rasin** [comment]
Plenty of projects mentioned/linked in pybind11 documentation not only don't follow one of the OSI-approved licenses, but are in fact actual commercial products: Visual Studio, macOS, Windows...

**Comment by wjakob** [comment]
These are major platforms that we unfortunately have to deal with, and it's impossible to hold them by the same standards for this project to be relevant. This discussion is not finished.

**Pull request closed without merging**
