### PR TITLE
[KNOWN TRAP]: segfault with stl.h wrapper for std::map (and no optimization enabled)

### PR DESCRIPTION
**Pull request by rhaschke**
## Description

When using both, a `Debug` build and the `stl.h` wrapper for `std::map`, I ran into a surprising segfault. 
I spent a whole day tracking that error down to pybind11 being compiled with no optimization options enabled.
I tried to come up with a minimal example reproducing exactly my issue - but I failed.

However, I was able to reproduce the issue in a different context. For now, this PR provides this minimal example.
What is really weird is that adding a new wrapper in `test_stl.cpp` triggers a bug in `test_stl_binders`.

Note, that I had to add additional gcc and clang build configs to CI (with optimizations disabled) to trigger the bug in Linux. On Windows, it shows up with the existing jobs already.

### CODE REVIEW

**Comment by rhaschke** [comment]
The backtrace of the segfault reveals that the `std::map` passed to C++ is corrupted for some reason. As the behavior is very different across different compilers, I am suspecting a compiler bug. I'm not sure though. I wasn't able to come up with a minimal example just moving `std::map` around.

In the build with debug output (1f0677a), it is interesting to compare both clang `C++14` builds:
- 🐍 3 • Clang 5 • C++14 • x64 [succeeds, _not_ instantiating `map_caster`](https://github.com/pybind/pybind11/actions/runs/3667495765/jobs/6199999288#step:7:817).
- 🐍 3 • Clang 10 • C++14 • x64 [fails, instantiating `map_caster`](https://github.com/pybind/pybind11/actions/runs/3667495765/jobs/6199999452#step:7:818)

**Comment by rhaschke** [comment]
I will work around this issue for now, by always ensuring some optimization options.
However, I just noticed that [all(?) gcc builds](https://github.com/pybind/pybind11/actions/runs/3667495765/jobs/6199997400#step:12:827) and [most Windows builds](https://github.com/pybind/pybind11/actions/runs/3667495765/jobs/6199997726#step:12:828) fail on that issue too when the map is actually used.

**Comment by rwgk** [comment]
Hi Robert, you seem to have an ODR violation:

* PR #4095 (CI just started, but see PR description with error from local testing)
* PR #4022

**Comment by rwgk** [comment]
I didn't realize this before: I'm afraid PR #4353 made it a lot more likely that ODR violations sneak in.

**Comment by rwgk** [comment]
Actually, no, I take that back, after taking a fresh look at stl_bind.h ... and the error message in the #4396 PR description (showing the source locations).

**Comment by rwgk** [comment]
The CI for #4396 is nearly complete. I'll close the PR soon, but the CI results will expire only later:

* https://github.com/pybind/pybind11/actions/runs/3667642607
* https://github.com/pybind/pybind11/actions/runs/3667642609

**Comment by rwgk** [comment]
> Where does that come from? Isn't including `pybind11/stl.h` and defining a wrapper with a `std::map` argument a valid approach?

It depends on how you compile & link.

Generally, there are three lines of defense against ODR violations:
* [pybind11 namespace hidden](https://github.com/pybind/pybind11/blob/9727dcdae5b723a01ec04bec5eb1a5a681cbb0fd/include/pybind11/detail/common.h#L84-L93)
* `-fvisibility=hidden`
* `RTLD_LOCAL` (default under Linux, a given under Windows (no other option), I'm not sure about macOS)

**But**

if you link multiple **Translation Units** (critical keyword when it comes to ODR) into one extension, all those defenses do not exist, on all platforms.  —  Note that most pybind11 unit tests are linked together as pybind11_tests.so. (You can [see that more clearly here](https://github.com/rwgk/pybind11_scons/blob/9c537b4c4ead8435ca62b763887bc967e370a088/SConscript#L113-L130) (compared to the cmake files).)

Specific to `type_caster` ODR violations, the critical code to consider is:

https://github.com/pybind/pybind11/blob/9727dcdae5b723a01ec04bec5eb1a5a681cbb0fd/include/pybind11/cast.h#L39-L40

It needs to resolve to the exact same template instantiations in all TUs linked together. (There is zero wiggle room for this, as [we learned the hard way](https://github.com/pybind/pybind11/pull/3862#issuecomment-1126377796).)

With this PR, the ODR arises from

* test_stl.cpp  —  `SourceLocation1="/usr/local/google/home/rwgk/forked/pybind11/include/pybind11/stl.h:161"`
* test_stl_binders.cpp 
 —  `SourceLocation2="/usr/local/google/home/rwgk/forked/pybind11/include/pybind11/detail/type_caster_base.h:913`

I.e. the `type_caster` specializations work out differently in the two TUs, and when those are linked together you get ODR violations.

I think of that has the "worst kind of trap set by pybind11". It really is not obvious.

One way to not have to worry about it so much: Set up your system with "one TU per extension". But that's not always feasible, then you have to think twice, and if things get really big (e.g. Google linking most things statically), test with the `type_caster_odr_guard` enabled (smart_holder branch only, but you can swap it in for testing without changing anything else).

**Comment by rhaschke** [comment]
I'm fine to close this issue report. However, you might want to check the ODR warnings popping up in the current master branch: https://github.com/pybind/pybind11/actions/runs/3659994679/jobs/6186623695

**Comment by rwgk** [comment]
> I'm fine to close this issue report. However, you might want to check the ODR warnings popping up in the current master branch: https://github.com/pybind/pybind11/actions/runs/3659994679/jobs/6186623695

Wow, thanks for pointing those out. Amazingly, I never noticed those before, even though I look at CI logs pretty regularly.

Continuing under PR #4398. I think it's a very different problem.

**Pull request closed without merging**
