### PR TITLE
WIP Replace macOS `-undefined dynamic_lookup`

### PR DESCRIPTION
**Pull request by rwgk**
## Description
Experimenting.

## Suggested changelog entry:

```rst

```

### CODE REVIEW

**Comment by rwgk** [comment]
No luck with these options, giving up for now.

```
[  9%] Linking CXX shared module pybind11_cross_module_tests.cpython-311-darwin.so
cd /Users/runner/work/pybind11/pybind11/tests && /Users/runner/hostedtoolcache/cmake/3.25.1/x64/cmake-3.25.1-macos-universal/CMake.app/Contents/bin/cmake -E cmake_link_script CMakeFiles/pybind11_cross_module_tests.dir/link.txt --verbose=1
/usr/local/opt/llvm/bin/clang++ -Os -DNDEBUG -isysroot /Applications/Xcode_14.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -bundle -Wl,-headerpad_max_install_names -Xlinker -framework -Xlinker CoreServices -Xlinker -framework -Xlinker IOKit -flto=thin -L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib -o pybind11_cross_module_tests.cpython-311-darwin.so CMakeFiles/pybind11_cross_module_tests.dir/pybind11_cross_module_tests.cpp.o 
...
undef: _PyBaseObject_Type
undef: _PyBuffer_Release
... long list ...
undef: __Py_NotImplementedStruct
undef: __Py_TrueStruct
Undefined symbols for architecture x86_64:
  "_PyBaseObject_Type", referenced from:
      pybind11::detail::get_internals() in lto.o
  "_PyBuffer_Release", referenced from:
      pybind11::buffer_info::~buffer_info() in lto.o
... very long list ...
```

**Comment by henryiii** [comment]
Last official word from Apple was there would be a solution in an upcoming Xcode, and there's no way to avoid the warning for now.

**Comment by rwgk** [comment]
> Last official word from Apple was there would be a solution in an upcoming Xcode, and there's no way to avoid the warning for now.

Thanks!

(That's an interesting way to handle a deprecation.)

**Comment by rwgk** [comment]
PR #4301 appears to be on track for solving the problem.

**Pull request closed without merging**
