### PR TITLE
Fix warning in C++17 mode.

### PR DESCRIPTION
**Pull request by bluescarni**
In C++17, static constexpr members are implicitly inline and it's deprecated to re-declare them outside the class. This fixes a GCC 7.2 ``-Wdeprecated`` warning in C++17 mode.

### CODE REVIEW

**Comment by wjakob** [comment]
Thank you -- this looks good to me.

**Comment by jagerman** [comment]
It looks good to me.  I've also pushed another commit to this branch that adds `-Wdeprecated` to the test suite to see if it catches anything else—assuming that passes the CI builds, this should be good to merge.

**Comment by jagerman** [comment]
Aha, that caught some more.  Another commit pushed to address them.

**Comment by bluescarni** [comment]
I got a few more methinks, but I cannot reproduce the eigen3 error on my setup.

**Comment by jagerman** [comment]
Perhaps it was fixed in 3.3.4; I've pushed a change to update it to see if that fixes it.  (Edit: forced pushed: the first attempt was broken).

**Comment by jagerman** [comment]
Okay, they are all solved now.  Upgrading to Eigen 3.3.4 didn't change anything, so I just disabled `-Wdeprecated` in `eigen.h`.

**Comment by jagerman** [comment]
This is now merged into `master` (outside of github to squash the commits properly) in ba33b2fc798418c8c9dfe801c5b9023d3703f417.

**Pull request closed without merging**
