### PR TITLE
Linux multiarch

### PR DESCRIPTION
**Pull request by jagerman**
This PR supersedes #519 (edit: whoops, not 518) with a few changes to make FindPythonLibsNew work properly on multiarch linux systems.

The main changes:
- The hard-coded PREFIX/lib and PREFIX/lib64 paths are gone in favour of using just LIBDIR
- If MULTIARCH is set, we also check LIBDIR/MULTIARCH (*before* LIBDIR)
- OS X doesn't need a special case (the non-Windows code now using LIBDIR seems to work perfectly well for OS X for both system and custom python installs)
- I renamed the PYTHON_LIBRARY_DIR variable to PYTHON_LIBDIR to avoid confusion with Python's package library directory.

### CODE REVIEW

**Comment by wjakob** [comment]
This looks great, thank you!

**Comment by wjakob** [comment]
Congratulations on commit 1000 🎉  ;)

**Comment by jagerman** [comment]
What happened? I was sure I saw 1001 when I looked a few minutes ago.

**Comment by wjakob** [comment]
I accidentally merged the PyPy WIP ;)

**Comment by dean0x7d** [comment]
Thanks @jagerman! Great solution.

**Pull request merged**
