### PR TITLE
pybind11_getbuffer: Fix Potential Nullptr Dereference

### PR DESCRIPTION
**Pull request by ax3l**
Fix a potential nullptr dereference of `obj`.

Found with [coverity](https://scan.coverity.com/dashboard) in a [downstream project](https://github.com/openPMD/openPMD-api).

### CODE REVIEW

**Comment by bstaletic** [comment]
@ax3l Only your team can actually see your dashboard, are we 100% sure this isn't a false positive? I know vim's codebase has some false positives.

**Comment by wjakob** [comment]
In what circumstance would ``obj`` be ``nullptr``? Generally not a fan of adding these types of checks everywhere just to make Coverity happy. (pybind11 is a header file library, so this will have an impact on the size of bindings in all projects using it).

**Comment by zhihaoy** [comment]
Later in the code there is a check to tell whether `view` is `nullptr`, so I guess it's may be legitimate to check `obj` as well.

**Comment by ax3l** [comment]
Since it's checked below it should also be checked before first accessing it at `Py_TYPE(obj)->tp_mro`, no?

**Comment by ax3l** [comment]
@bstaletic sure, if you like I can give you access (gitter me, I think via mail). I just did not filter my "thirdParty" dir, that's why they show up and they look useful, regarding public struct members.
Of course, the question stands as @wjakob states correctly for structs that are only used with "init-wrapper" c-style functions, but I think most of the constructor init does not hurt.

**Comment by bstaletic** [comment]
@ax3l is right. Currently, on line 466 `obj` is dereferenced, but is checked against `nullptr` only later on line 471. Since NULL dereference isn't allowed in valid C or C++, compiler is allowed to remove all null checks after dereferencing, assuming that they aren't true. Therefore, from a formally correct C++ stand point, the line 471 might as well have `obj == nullptr` removed. Either pybind needs to check if `obj` is NULL earlier, or assume it never will be NULL. Either way the `obj == nullptr` on line 471 is useless.

**Comment by ax3l** [comment]
Alternative implementation following @wjakob's comment about `obj` being [safe by contract](https://github.com/pybind/pybind11/pull/1657#issuecomment-452090058) in #1664

**Comment by wjakob** [comment]
Closing this as #1664 was merged.

**Pull request closed without merging**
