### PR TITLE
Fix auto type deduction failures when var name is an existing type name

### LINKED ISSUE #1381: Unable to compile with PGI C++ due to `auto` deduction failures
Hello,

The latest free version of PGI compilers was released today. I tried to compile with it a simple pybind11 program but I get a bunch of errors. By "simple program" I mean just including `<pybind11/pybind11.h>`. Here is the output with all the errors: https://pastebin.com/jeCNBwWx
All the errors are cause by lines where something is cast to `auto`. After going through the files and manually typing the types, I was able to compile the simple example found at http://pybind11.readthedocs.io/en/master/basics.html#creating-bindings-for-a-simple-function

The changes I performed are the following:

File: `include/pybind11/detail/class.h`:
multiple lines: replace `auto` in `reinterpret_cast<detail::instance *>` lines with `detail::instance*`
517: `auto` -> `object`
554: `auto` -> `PyObject*`
561: `auto` -> `PyTypeObject*`

File: `include/pybind11/detail/init.h`:
27: `auto` -> `pybind11::detail::descr<1UL, pybind11::detail::value_and_holder>`

File: `include/pybind11/pybind11.h`:
741: `auto` -> `dict`

It appears that the PGI C++ compiler fails to deduct types when using the `auto` keyword in some places. To me, the pybind11 code I edited seems standard C++, but at the same time I am not a C++ expert. Can someone verify that the problem here is the PGI compiler and not some non-standard C++ used in pybind11?

Best Regards,
George

### PR DESCRIPTION
**Pull request by chuckatkins**
This is the continuation of #1431 and fixes #1381.

While this does address the PGI type deduction issues, pybind11 still won't correctly build with PGI without #1428.

### CODE REVIEW

**Comment by chuckatkins** [comment]
Noite that once #1428 is merged I'll rebase this and it should be ready to go.

**Comment by jagerman** [comment]
Have you reported this bug to PGI?  We can work around it, of course, but it's definitely a compiler bug.

**Comment by wjakob** [comment]
Hi @chuckatkins,

I've merged the first commit (a899dd0). The second (Utilize CMake's language standards abstraction when possible) is superseded by a larger PR that is still in the queue.

Regarding the third (work around PGI compiler bugs by making changes throughout pybind11) -- sorry, no :(. If this was one of the major 3 (GCC, Clang, MSVC), I would be more open to this sort of thing.

Best,
Wenzel

**Comment by ax3l** [comment]
@chuckatkins can you confirm [PGI 18.7+](https://github.com/pybind/pybind11/issues/1381#issuecomment-411805050) fixed the compiler bug?

**Pull request closed without merging**
