### PR TITLE
enable IDEs such as Qt Creator to list headers files in the project tree

### PR DESCRIPTION
**Pull request by drufat**
Keep headers files as a source only target in order to enable IDEs to list them in the project tree. See [1] for more details.

[1] http://stackoverflow.com/questions/28384935/qtcreator-cmake-project-how-to-show-all-project-files

### CODE REVIEW

**Comment by wjakob** [comment]
Actually, the second answer from that stackoverflow thread is the way to go. Adding a fake custom target feels very unnatural to me.

**Comment by wjakob** [comment]
(this could be done by adding the headers to the target created in ``pybind11_add_module``)

**Comment by drufat** [comment]
Ok, I followed your suggestion about adding the header files to the target in `pybind11_add_module`:

https://github.com/drufat/pybind11/commit/3b86486386ba58bbac5f6fe3a428f59856965504

Should I create a new pull request?

**Comment by wjakob** [comment]
Yes, please do.

**Pull request closed without merging**
