### PR TITLE
New issue, when registering type multiple times.

### PR DESCRIPTION
**Pull request by abergmeier**
Ideally, the module should fail when loading IMO.

### CODE REVIEW

**Comment by abergmeier** [comment]
@wjakob Should I rewrite the test to provoke 38d8b8c behavior?

**Comment by wjakob** [comment]
There is a test now which does this, no?

**Comment by wjakob** [comment]
The updated test suite has a test which validates that a class can't be defined twice. That is enough, no?

**Comment by abergmeier** [comment]
Should be fine.

**Pull request closed without merging**
