### PR TITLE
fix: replace free() with std::free()

### LINKED ISSUE #3315: [BUG]: `free()` used instead of `std::free()`
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### Problem description

https://github.com/pybind/pybind11/blob/master/include/pybind11/pybind11.h#L1539
https://github.com/pybind/pybind11/blob/master/include/pybind11/pybind11.h#L1547

`free()` here is ambiguous whereas the rest of the code explicitly references `std::free()`. This clashes with some other frameworks that implement their own `free()` e.g. NVIDIA's framework (FW)

Fix: change the two lines to reference `std:free()` instead.

### Reproducible example code

```text
N/A
```

### PR DESCRIPTION
**Pull request by Skylion007**
## Description
* Closes #3315 . Use std::free instead of the ambiguous free().

## Suggested changelog entry:

```rst
* Ensure that std::free() is used consistently throughout the code base.
```

### CODE REVIEW

**Review by rwgk — COMMENTED** [review]
It would be ideal to also add `#include <cstdlib>` at the top of the two changed files (IWYU). As-is, the include only comes in indirectly via pybind11/detail/typeid.h.

**Review by rwgk — APPROVED** [review]
Looks good to me.

I hope the eigen download issue will resolve itself soon, so that we can be sure this works everywhere.

**Review by henryiii — APPROVED** [review]

**Comment by henryiii** [comment]
Screen Shot 2021-10-03 at 10 23 45 AM

**Comment by rwgk** [comment]
Looks like a major technical issue (below). They seem to have lost the entire repo.

I'll clone the PR, set download eigen off. That should be sufficient to convince us that this PR is good.

https://gitlab.com/libeigen/eigen

Screen Shot 2021-10-03 at 14 51 40

**Comment by rwgk** [comment]
https://github.com/pybind/pybind11/pull/3324

**Comment by rwgk** [comment]
Success with all `-DDOWNLOAD_EIGEN=OFF`:

* CI: https://github.com/pybind/pybind11/actions/runs/1301470881
* Format: https://github.com/pybind/pybind11/actions/runs/1301470878

This PR is definitely safe to merge.

**Pull request merged**
