### PR TITLE
Typed iterators

### PR DESCRIPTION
**Pull request by aldanor**
This has turned out to be quite a bit more work than I initially expected it to be, but here goes.
- `iterator_t<T>` is a typed iterator that casts each item to `T`
- `iterable_t<T>` is a typed iterable
- `sequence_t<T>` is a sized typed iterable
- Iterators can now be passed directly to STL (see the test example)
- `sequence` / `sequence_t` can now be used as a function argument
- `array<T, n>` is now loadable from sequences 

Previous discussion: in #360.

### CODE REVIEW

**Comment by aldanor** [comment]
Tbh I have no idea what the obscure Travis failure is about: https://travis-ci.org/pybind/pybind11/jobs/169839362

**Comment by jagerman** [comment]
> Tbh I have no idea what the obscure Travis failure is about: ...

Try moving the `#include <algorithm>` below the pybind11 includes (so that Python.h gets included (via pybind11/common.h) before anything else).

**Comment by aldanor** [comment]
@jagerman Thanks, that helped :) Seems to be green now.

**Comment by dean0x7d** [comment]
Would overload resolution work?
```c++
m.def("sort_iterable_t", [](py::iterable_t<std::string> it) { ... }
m.def("sort_iterable_t", [](py::iterable_t<int> it) { ... }
```
```python
>>> sort_iterable_t([1, 2, 3])
# error?
```

**Comment by aldanor** [comment]
Yep error, I think (haven't checked though). Good point, but not sure how it could possibly work here because it's lazy -- it would have to iterate over the sequence first to figure if it matches the type...

**Comment by dean0x7d** [comment]
As it is now `iterable_t` is a full `py::object`, but does it need to be? Could it just be something returned by `iterable`? For example:
```c++
m.def("foo", [](py::iterable it) {
    for (auto s : it.iterate_as<std::string>()) {
        // ...
    }
});
```
The class returned by `iterator::iterate_as<T>` would only need to be a C++ iterator and it wouldn't need all the `object_api` functions. This could simplify the implementation and make it impossible to use the typed iterator as a function parameter, thus avoiding any surprising overload behavior.

**Comment by aldanor** [comment]
Hm yes good point, I'll try playing around with that idea. Wonder if `iterator_t` still needs to be a `py::object`, or maybe just hold a handle to the actual `iterator` instead?

**Comment by dean0x7d** [comment]
Yeah, I think both `iterable_t ` and `iterator_t` don't need to be derived from `py::object`. It's enough to have the C++ iterable/iterator interface. (I mixed up iterable and iterator half way thought my last post.)

**Comment by wjakob** [comment]
> As it is now iterable_t is a full py::object, but does it need to be?

I agree with this. I consider multiple inheritance a C++ feature best used in moderation (and preferably not at all). It would be nice to avoid using it in the core bits of pybind11.

**Comment by wjakob** [comment]
This PR has been dormant for quite a while. I'll close it for now but am perfectly happy to review it again it in case it is updated.

**Pull request closed without merging**
