### PR TITLE
[smart_holder] WIP: Fix for Python 3.9 MSAN/valgrind errors.

### PR DESCRIPTION
**Pull request by rwgk**
WIP — Currently this is NOT A FIX, just hoping to become one.

### CODE REVIEW

**Comment by henryiii** [comment]
Please prefix all PRs to non-master with `[branch-name]`. :)

**Comment by rwgk** [comment]
> Please prefix all PRs to non-master with `[branch-name]`. :)

Done and will do.
FWIW: this one has a chance to turn into a PR against master, but not sure until we have an actual fix + reproducer.

**Comment by henryiii** [comment]
That's fine, but that will be a new PR (or at least a changed PR), so the name can be different. :)

**Comment by rwgk** [comment]
Drive-by cleanup: closing.

I was told the root issue was fixed in Python 3.9.something. I assume the fix trickled through the system in the meantime. Any more work here isn't going to be of great help to world at large.

**Pull request closed without merging**
