### PR TITLE
fix: emscripten cmake issue

### PR DESCRIPTION
**Pull request by henryiii**
## Description

Emergency fix for bug in Emscripten support causing failures. Config mode is not supported due to a typo.

## Suggested changelog entry:

```rst
* Fix typo in Emscripten support when in config mode (CMake)
```

### CODE REVIEW

**Review by rwgk — APPROVED** [review]
Oh ... I saw that underscore but thought it's intentional.

What does that mean for the 2.13.2 release?

**Comment by henryiii** [comment]
It was left over from when I had `_pybind11_is_config`, a variable set in the files calling this file (which I might move to after this).

> 2.13.2

It means I'm about to release 2.13.3. I don't think we need to yank 2.13.2, as this only affects Pyodide.

I'm trying to test this in a boost-histogram PR to make sure the fix works; our CI only is testing the "CMakeLists.txt" mode and not the pybind11Config mode for Pyodide.

**Comment by rwgk** [comment]
> It means I'm about to release 2.13.3

Sounds good.

**Comment by henryiii** [comment]
Works: https://github.com/scikit-hep/boost-histogram/actions/runs/10373050070/job/28717229907?pr=950

**Pull request merged**
