### PR TITLE
iterator next implemented using prefix operator.

### PR DESCRIPTION
**Pull request by rhl-**
This makes all the iterator ranges in my bindings work correctly.

### CODE REVIEW

**Comment by rhl-** [comment]
im not too sure what I broke here. does the python iterator binding fail to implement the prefix operator?

**Comment by rhl-** [comment]
Ah, I see what is wrong. Somehow the python iterator is skipping the first element of the sequence. Not sure how to fix it offhand.. looking into it.

**Comment by rhl-** [comment]
Ok, this is perhaps suboptimal, but I think its correct. Perhaps @wjakob can optimize it.

**Comment by wjakob** [comment]
After collapsing all of the diffs here into one, I'm confused. There are quite a few changes where

1. It's not clear that all of them are truly needed
2. Your code throws exceptions in multiple places, in a way that doesn't make sense to me
3. Is not formatted properly
4. It's still not clear to me, specifically, what was wrong with the previous post-increment operator. Couldn't it be that there is just a problem with how the iterators in your codebase are implemented?

Before fixing something in pybind11, it needs to be clear what the issue with the original code was. The issue + PR together read to me as "Didn't work before now -- works with this patch", which I don't find good enough of a justification.

(I'm not saying that you're wrong -- I'm just not convinced.)

**Comment by wjakob** [comment]
Can you check if commit e6ab92c52a5102a331f0bf33469bc53addf8b755 does anything regarding your issue?

**Comment by rhl-** [comment]
It does not appear to. When I finish this paper ( hopefully this week) I
will create a proper bug report.

**Comment by wjakob** [comment]
any news here?

**Comment by wjakob** [comment]
Closing this for now as the issue is a month old now. Feel free to reopen/comment when there is some new information.

**Pull request closed without merging**
