### PR TITLE
Make a 2.2.2 release

### PR DESCRIPTION
**Pull request by jagerman**
I think we've accumulated more than enough fixes to make a 2.2.2 release; this PR (against the v2.2 branch) is just the appropriate commits cherry-picked from `master` (and doesn't add anything new aside from the changelog and version variables bump).

If anyone knows of some critical fix that I missed in this PR, or some other issue that needs to be fixed for 2.2.2, now is the time to speak up to get it included.

### CODE REVIEW

**Comment by jagerman** [comment]
Pushed a couple fixes for a new MSVC `/permissive-` error reported in #1239.  (That this warning comes up in the first place smells like an MSVC bug, but the workaround is easy and allows removing a bunch of now-unnecessary `detail::` qualifications).

**Comment by jagerman** [comment]
Added 89cb495 (and updated the changelog), which is an equivalent to #1253 (for issue #1251), backported to 2.2 so as to leave the patients list as a vector (and walking through it to look for and avoid storing duplicate patients).

**Comment by wjakob** [comment]
This all looks good to me, I will push out the release shortly.

**Comment by wjakob** [comment]
Done. 2d0507db43cd5a117f7843e053b17dffca114107 adds the changelog to the main branch.

**Pull request merged**
