### PR TITLE
Multiple inheritance fixes

### LINKED ISSUE #801: Incorrect objects construction with multiple inheritance
I've decided to open a new issue, following already closed #797, because I was able to narrow down the error case and I think it's related to multiple inheritance and/or incorrect usage of trampolines, which I cannot detect.

Here's modified test case from #797:
```C++
#include <pybind11/pybind11.h>
#include <iostream>

namespace py = pybind11;
using namespace pybind11::literals;

// classes
class objbase : public std::enable_shared_from_this< objbase > {
	int prop_ = 42;
public:
	virtual std::string name() const {
		return "objbase";
	}

	int prop() const { return prop_; }
};

class iface {
public:
	int n = 42;
	virtual int f() const = 0;
};

class mytype : public iface, public objbase {
public:
	std::string name() const override {
		return "mytype";
	}
	int f() const override {
		return 42;
	}
};
using sp_my = std::shared_ptr<mytype>;
using sp_cmy = std::shared_ptr<const mytype>;

// trampoline
template<class T = objbase>
class py_objbase : public T {
public:
	using T::T;

	std::string name() const override {
		PYBIND11_OVERLOAD(std::string, T, name);
	}
};

class py_objbase_ : public py_objbase<> {
	double pyprop_ = 42.84;

public:
	using py_objbase<>::py_objbase;

	double pyprop() const { return pyprop_; }
};

class py_iface : public iface {
public:
	using iface::iface;

	int f() const override {
		PYBIND11_OVERLOAD_PURE(int, iface, f);
	}
};

// bind mytype
class py_mytype : public py_iface, public py_objbase<mytype> {
public:
	using py_objbase<mytype>::py_objbase;

	int f() const override {
		PYBIND11_OVERLOAD(int, mytype, f);
	}
};

PYBIND11_PLUGIN(example) {
	py::module m("example");

	// bind objbase
	py::class_<objbase, py_objbase_, std::shared_ptr<objbase>>(m, "objbase", py::multiple_inheritance())
		.def(py::init_alias<>())
		.def("name", &objbase::name)
		.def_property_readonly("prop", &objbase::prop)
		.def_property_readonly("refs", [](const objbase& src) { return src.shared_from_this().use_count() - 1; })
		.def_property_readonly("pyprop", [](const objbase& src) {
			return static_cast<const py_objbase_*>(&src)->pyprop();
		})
	;

	// iface
	py::class_<iface, py_iface, std::shared_ptr<iface>>(m, "iface", py::multiple_inheritance())
		.def("f", &iface::f)
	;

	// bind mytype
	py::class_<mytype, iface, objbase, py_mytype, sp_my>(m, "mytype", py::multiple_inheritance())
		.def(py::init<>())
		.def("name", &mytype::name)
		.def("f", &mytype::f)
		.def_property_readonly("n", [](mytype& src){ return src.n; })
	;

	return m.ptr();
}
```
The main difference from #797 is that `objbase` now has `py_objbase_` trampoline instead of `py_objbase<>`. And `py_objbase_`, in it's turn, contains specific variable `pyprop`.

Now, if `objbase` is constructed directly, everything is fine:
```Python
In [1]: import example as e

In [2]: a = e.objbase()

In [3]: a.pyprop
Out[3]: 42.84
```
But `mytype` is constructed incorrectly:
```Python
In [1]: import example as e

In [2]: a = e.mytype()

In [3]: a.pyprop
Out[3]: 4.65557599738463e-310
```
More that that, in this concrete example if I change `mytype`'s constructor from `.def(py::init<>())` to `.def(py::init_alias<>())`, then Python crashes with segfault on `a = e.mytype()` line.

As you can see, I've added `multiple_inheritance()` tag to all exported types, but it makes no difference at all, because it makes sense only for `mytype` which already has multiple bases specified as `class_` template arguments.

Testes on clang 3.9.1, Python 2.7.13.

### PR DESCRIPTION
**Pull request by jagerman**
This fixes two issues with multiple inheritance.

The first is that when we cast a base class pointer, we correctly detect (via a `typeid`) the derived class, but then do (in essense) a reinterpret_cast on it, which is wrong when the base class is offset (due to multiple inheritance).  The fix is to dynamic_cast to the most derived type before passing the pointer on.

The second fix is that we can often end up with multiple Python instances around the same C++ instance when we are given a base class pointer in the same situation as above: the pointer doesn't match anything in `registered_instances`, so we treat it as a new type, even though, internally, it is really wrapping the same type.  The commit to fix this adds into `registered_instances` all the base type pointers (for base types that we know about) that aren't equal to the derived pointer.  This is a bit of extra work as we have to do it recursively, and both during registering the instance and deregistering, but this is only done for types that actually have multiple bases somewhere above them in their inheritance tree.

Fixes #801.

@uentity - I think this should fix at least some of your multiple inheritance issues; your feedback here would be very valuable.

### CODE REVIEW

**Comment by uentity** [comment]
@jagerman I thought I have found a solution by playing with casts inside `init_holder_helper()` (you can check it in my updated commit  for PR #806). But then this PR appeared and I tried to run your tests and they failed.

I think your proposal is versatile and address the problem in its toots. Tomorrow I'll check it in my real-world project, but it has to work.

**Comment by jagerman** [comment]
I found another problem here, when returning an derived instance of an unregistered type as an offset base class pointer to a registered type.  We would cast to most-derived, pass that to `cast(...)`, which would then recognize that the type is unregistered and so cast it to the backup type.  But that isn't valid: by the time we get to `cast()` there's no way to get back to the base class pointer.

The update moves the type decision logic out of cast entirely: we should dynamic cast if the type is polymorphic *and* a registered type; otherwise we don't dynamic_cast at all, keeping the `itype` pointer as-is, and use `itype` as the type.  (The updated commit also adds another a test that triggers this case).

**Comment by uentity** [comment]
All my code works even without your latest update, and update didn't break it either. My issue #801 is solved.

**Comment by jagerman** [comment]
The latest update is a bit of an obscure case: you'd have to have something like:
```
 B   C
  \ /
   A
```
where A is *not* pybind11-registered, but `C` is, and you return a `C` pointer to an `A` instance.  (Whether or not `B` is pybind11-registered doesn't matter; if it is, nothing would have broken when returning a `B *` because it happens to be valid in that case to reinterpret_cast an `A *` back to `B *`).

**Comment by uentity** [comment]
It's great that pybind11 finally correctly manages even such a corner cases with multiple inheritance. Thumbs up!

**Pull request merged**
