### PR TITLE
Issue #1532: Incompatible config options, /MP vs /Gm for MSVC in DEBUG

### PR DESCRIPTION
**Pull request by paamand**
Added a cmake generator expression for /MP flag to only be set in RELEASE.

### CODE REVIEW

**Comment by wjakob** [comment]
Can you comment on why? Also, note that there are other release mode builds (e.g. with debug info, min. size) where the parallel build makes sense.

**Comment by wjakob** [comment]
Ah, I see the title now. The question then is which of the (four?) CMake build modes adds /Gm.

BTW: What I don't understand is why the AppVeyor build succeeds if the flags are incompatible as you say.

**Comment by paamand** [comment]
It's only a warning. MSVC prints the warning about ignoring /Gm, which is probably why it suceedes?
From [https://msdn.microsoft.com/en-us/library/bb385193.aspx](https://msdn.microsoft.com/en-us/library/bb385193.aspx)
"The /Gm Compiler Option
By default, a project build enables the /Gm compiler option (incremental builds) for debug builds, and disables it for release builds. Therefore, the /MP compiler option is automatically disabled in debug builds because it conflicts with the default /Gm compiler option."

**Comment by wjakob** [comment]
Could you change the condition so that /MP is added if the mode is /not/ debug, rather only in release mode? There are other builds (e.g. MinSizeRel) where the parallelism is helpful.

**Comment by wjakob** [comment]
Thanks!

**Pull request merged**
