### PR TITLE
test object tracking

### PR DESCRIPTION
**Pull request by district10**
## Description

`id(reference_internal_obj)` is not stable under python 3.9+.

Related issue: <https://github.com/pybind/pybind11/issues/4425>

## Suggested changelog entry:

```rst

```

### CODE REVIEW

**Comment by Lalaland** [comment]
Interesting, your added test seems to pass fine on our CI infrastructure

**Comment by district10** [comment]
> Interesting, your added test seems to pass fine on our CI infrastructure

😢 Weird. Something wrong with my compiler or python (conda)? I reproduced error locally.

**Comment by district10** [comment]
I'm testing on [cmake_example](https://github.com/district10/cmake_example/commit/9e293fa5ceadb7c7df07466f5a6c6ef2c7db1a21), and find something interesting.

It seems related to python GC.

All following three tests conducted on python 3.8 (not even 3.9 as reported)

## tests/test_id.py

```python
import cmake_example as m

p = m.Pod()
ids = set()
for idx, _ in enumerate(range(5)):
    ids.add(id(p.beed()))
print(ids)
# {139655559748720}
```

## tests/test_id_slow_gc.py

```python
import cmake_example as m

p = m.Pod()
ids = set()
for idx, _ in enumerate(range(5)):
    bid = id(p.beed())
    print(idx, bid)
    ids.add(bid)
print(ids)
# 0 139725064776816
# 1 139725064776880
# 2 139725064776880
# 3 139725064776880
# 4 139725064776880
# {139725064776816, 139725064776880}
# it's weird always **two** ids
```

## tests/test_id_no_gc.py

When you hold object preventing GC, all things go normal.

```python
import cmake_example as m

p = m.Pod()
objs = []
ids = set()
for idx, _ in enumerate(range(5)):
    objs.append(p.beed())
    bid = id(objs[-1])
    print(idx, bid)
    ids.add(bid)
print(ids)
# 0 139761325399280
# 1 139761325399280
# 2 139761325399280
# 3 139761325399280
# 4 139761325399280
# {139761325399280}
```

> Python and C++ use fundamentally different ways of managing the memory and lifetime of objects managed by them.
>
> https://pybind11.readthedocs.io/en/stable/advanced/functions.html

All pybind11 object has two parts, one on c++ land and the other on python land.
The python part always points to one c++ object, but can be new object itself.
And `id(obj)` reflects python object id, not c++ object id.

**Comment by district10** [comment]
So It's more like I misused `id`.

> This identity has to be unique and constant for this object during the lifetime. **Two objects with non-overlapping lifetimes may have the same id() value.**

By the way, how I can I get the c++ object id or memory address?

**Comment by rwgk** [comment]
pybind11 has a registry for wrapped instances, mapping a C++ pointer to a `PyObject*`.

When returning a C++ object, before creating a new `PyObject`, the registry is inspected, and the existing `PyObject*` returned if it exists (https://github.com/pybind/pybind11/blob/70af9873c26ea46cf97d66444f4d80c4af79dd7a/include/pybind11/detail/type_caster_base.h#L524-L526). That explains your observation:

> When you hold object preventing GC, all things go normal.

But if the wrapped object goes out of scope (the reference count hits 0), it is deleted from the registry, therefore you get a new `PyObject` each time in your loop in test_id_slow_gc.py. It's just chance if the new object has the same `id` as before, as you found out already.

I think: everything is working as intended.

> By the way, how I can I get the c++ object id or memory address?

Probably best to use a trick (untested): `.def("pass_bead", [](const bead *ptr) { <use ptr here> });`

Or you need to extract a couple lines from type_caster_base.h, e.g. around here **I think**:

https://github.com/pybind/pybind11/blob/70af9873c26ea46cf97d66444f4d80c4af79dd7a/include/pybind11/detail/type_caster_base.h#L694

**Comment by district10** [comment]
@rwgk Thank you so much for your detailed reply.

> By the way, how I can I get the c++ object id or memory address?

Your trick seems easier for me to implement, I would just bind a function to export pointer address as size_t.

Now, I close this PR.

**Pull request closed without merging**
