### PR TITLE
Allow None for char * and wchar_t *

### PR DESCRIPTION
**Pull request by hulucc**
Use const char * as the value type of type_caster<char> so that Py_None can be passed to char * type parameter, also nullptr can be used as default argument when binding to char *.

The feature has been mentioned in #108. I'm not sure why pybing11 doesn't allow it.But i think it's extremely useful when binding to some old style c++ code or c api, so i create this PR.

### CODE REVIEW

**Comment by wjakob** [comment]
Please squash your changes into a proper commit :)

**Comment by wjakob** [comment]
Right now it's impossible to see what is going on with all the commenting and code duplication...

**Comment by hulucc** [comment]
Ok, i squash it to b8bce7b now

**Comment by wjakob** [comment]
Hi -- I ended up implementing this more compactly, see 9883ec0.

**Pull request closed without merging**
