### PR TITLE
Clarify difference between Py 2 & Py 3. Mention that Anaconda fails.

### PR DESCRIPTION
**Pull request by cjrh**
I spent many hours on this today.  Some small additions to the docs might be useful for other people so that they don't struggle down the same dead ends.

### CODE REVIEW

**Comment by cjrh** [comment]
Hmm.  I see now that there have been several other issues in which Anaconda details have been mentioned:

https://github.com/pybind/pybind11/issues?utf8=%E2%9C%93&q=is%3Aissue+anaconda

**Comment by cjrh** [comment]
Is there currently a way that a conda env can work with pybind11? I tried a bunch of things and I could not get `example.so` to link properly to `libpython3.5m.dylib` at runtime.

**Comment by wjakob** [comment]
I'll cc @SylvainCorlay who is the resident conda expert :)

**Comment by cjrh** [comment]
Well in that case I had better give more information!  The linking setup for the Python module looks like this:

```bash
🎨  ~/anaconda/envs/py35/lib
calebhattingh $ otool -L libpython3.5m.dylib
libpython3.5m.dylib:
	libpython3.5m.dylib (compatibility version 3.5.0, current version 3.5.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 111.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 476.0.0)
	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```

This is OS X 10.11.5.  This conda env above is with Python 3.5.1.  Using the beginner example in the pybind11 docs, I could successfully _compile_ `example.cpp` into `example.so`, but importing it into a running interpreter would fail.  Specifically, the error message was that the python dylib could not be found.  The dynamic linking info inside `example.so` simply duplicated what was available in the Python version above.

This is different to what you get with, e.g., a homebrew python.  In this case, the linking information looks like this:

```
🎨  ~
calebhattingh $ otool -L /usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/libpython3.5m.dylib
/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/libpython3.5m.dylib:
	/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.5/Python (compatibility version 3.5.0, current version 3.5.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1258.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

Note that the full path to `libpython3.5m.dylib` is listed in the linking information.   When you compile and link `example.so`, this also gets copied into the image:

```
🎨  ~/workspace/scratch/pybind11
calebhattingh $ otool -L example.so
example.so:
	example.so (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.5/Python (compatibility version 3.5.0, current version 3.5.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1258.1.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
```

Using the homebrew python, the example worked flawlessly.

So getting back to the conda version.  I tried these things, unsuccessfully:
- Putting `~/anaconda/envs/py35/lib` on my system path`
- Using `install_name_tool` to change the linking information inside `example.so` to something like `@rpath/libpython3.5m.dylib`

Is there something obvious I'm missing?

[Sidenote: I've also spent several hours today fighting with YouCompleteMe to get it linking with the right version of python, which must match the one Vim is linked to, etc, etc.  Linking problems eat up so much of my time :(]

**Comment by wjakob** [comment]
So I'll just mention that the CMake build system uses a trick to never link against a specific version of the Python library via ``-undefined dynamic_lookup`` (take a look around line 68+), which can save the day on OSX.

**Comment by cjrh** [comment]
The problems begin quite early.  For example, the `c++` invocation in the docs for the example immediately fails by being unable to the python library during linking.  I got around this by adding a `-L` switch to the compilation line, but perhaps this indicates that there are additional things wrong with my setup:

```
🎨  ~/Dropbox/Technical/codelibs/workspace/scratch/pybind11
calebhattingh $ ls
example.cpp
🎨  ~/Dropbox/Technical/codelibs/workspace/scratch/pybind11
calebhattingh $ . activate py35
discarding /Users/calebhattingh/anaconda/bin from PATH
prepending /Users/calebhattingh/anaconda/envs/py35/bin to PATH
(py35)🎨  ~/Dropbox/Technical/codelibs/workspace/scratch/pybind11
calebhattingh $ c++ -O3 -shared -std=c++11 -I ~/Documents/repos/pybind11/include `python3-config --cflags --ldflags` example.cpp -o example.so
In file included from example.cpp:19:
In file included from /Users/calebhattingh/Documents/repos/pybind11/include/pybind11/pybind11.h:32:
In file included from /Users/calebhattingh/Documents/repos/pybind11/include/pybind11/attr.h:13:
In file included from /Users/calebhattingh/Documents/repos/pybind11/include/pybind11/cast.h:13:
/Users/calebhattingh/Documents/repos/pybind11/include/pybind11/pytypes.h:43:7: warning:
      use of the 'deprecated' attribute is a C++14 extension
      [-Wc++14-extensions]
    [[deprecated("call(...) was deprecated in favor of operator()(...)")]]
      ^
1 warning generated.
ld: library not found for -lpython3.5m
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by cjrh** [comment]
Then, if I manually provide the path to the lib (using `-L`), a different error occurs regarding the switches being used, which may have to do with something that's different between `python3-config` and `python-config`:

```
(py35)🎨  ~/Dropbox/Technical/codelibs/workspace/scratch/pybind11
calebhattingh $ c++ -O3 -shared -std=c++11 -I ~/Documents/repos/pybind11/include -L /Users/calebhattingh/anaconda/envs/py35/lib/ `python3-config --cflags --
ldflags` example.cpp -o example.so
In file included from example.cpp:19:
In file included from /Users/calebhattingh/Documents/repos/pybind11/include/pybind11/pybind11.h:32:
In file included from /Users/calebhattingh/Documents/repos/pybind11/include/pybind11/attr.h:13:
In file included from /Users/calebhattingh/Documents/repos/pybind11/include/pybind11/cast.h:13:
/Users/calebhattingh/Documents/repos/pybind11/include/pybind11/pytypes.h:43:7: warning:
      use of the 'deprecated' attribute is a C++14 extension
      [-Wc++14-extensions]
    [[deprecated("call(...) was deprecated in favor of operator()(...)")]]
      ^
1 warning generated.
ld: -stack_size option can only be used when linking a main executable
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

**Comment by cjrh** [comment]
So then I figure I should alter the output of `python3-config` to remove the `stack_size` switch, which means I create a small build script that looks like this:

```bash
# build.sh
 c++ -O3 -shared -std=c++11 \
     -I/Users/calebhattingh/Documents/repos/pybind11/include \
     -fno-strict-aliasing -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes \
     -I/Users/calebhattingh/anaconda/envs/py35/include \
     -arch x86_64 \
     -L/Users/calebhattingh/anaconda/envs/py35/lib \
     -lpython3.5m \
     -ldl -framework CoreFoundation \
     -o example.so

     # -Wl,-stack_size,1000000 \        <--- OUT OF ACTION
```

This works!

```
(py35)🎨  ~/Dropbox/Technical/codelibs/workspace/scratch/pybind11
calebhattingh $ sh build.sh
(py35)🎨  ~/Dropbox/Technical/codelibs/workspace/scratch/pybind11
calebhattingh $ ls
build.sh    example.cpp example.so
```

Unfortunately, I can't import the extension successfully:

```
(py35)🎨  ~/Dropbox/Technical/codelibs/workspace/scratch/pybind11
calebhattingh $ python
Python 3.5.1 |Anaconda custom (x86_64)| (default, Dec  7 2015, 11:24:55)
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import example
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/calebhattingh/Dropbox/Technical/codelibs/workspace/scratch/pybind11/example.so, 2): Library not loaded: libpython3.5m.dylib
  Referenced from: /Users/calebhattingh/Dropbox/Technical/codelibs/workspace/scratch/pybind11/example.so
  Reason: image not found
```

This is the linking information in `example.so`:

```
(py35)🎨  ~/Dropbox/Technical/codelibs/workspace/scratch/pybind11
calebhattingh $ otool -L example.so
example.so:
        example.so (compatibility version 0.0.0, current version 0.0.0)
        libpython3.5m.dylib (compatibility version 3.5.0, current version 3.5.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
        /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1258.1.0)
        /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
```

Note that the Python lib is on my path (I added that dir to my path just for these tests; it isn't there by default with conda envs):

```
calebhattingh $ which libpython3.5m.dylib
/Users/calebhattingh/anaconda/envs/py35//lib//libpython3.5m.dylib
```

So at this point I played with a few tricks that didn't work.

**Comment by cjrh** [comment]
_Finally_: if I just use the homebrew Python 3 (currently 3.5.1), it Just Works, without any fiddling, exactly as per the docs, no `stack_size` problems or anything like that:

```
🎨  ~/Dropbox/Technical/codelibs/workspace/scratch/pybind11
calebhattingh $ c++ -O3 -shared -std=c++11 -I ~/Documents/repos/pybind11/inclu
de `python3-config --cflags --ldflags` example.cpp -o example.so
In file included from example.cpp:19:
In file included from /Users/calebhattingh/Documents/repos/pybind11/include/pybind11/pybind11.h:32:
In file included from /Users/calebhattingh/Documents/repos/pybind11/include/pybind11/attr.h:13:
In file included from /Users/calebhattingh/Documents/repos/pybind11/include/pybind11/cast.h:13:
/Users/calebhattingh/Documents/repos/pybind11/include/pybind11/pytypes.h:43:7: warning:
      use of the 'deprecated' attribute is a C++14 extension
      [-Wc++14-extensions]
    [[deprecated("call(...) was deprecated in favor of operator()(...)")]]
      ^
1 warning generated.
🎨  ~/Dropbox/Technical/codelibs/workspace/scratch/pybind11
calebhattingh $ python3
Python 3.5.1 (default, May  2 2016, 20:04:08)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import example
>>> example.add(1,2)
3
```

**Comment by cjrh** [comment]
I'm probably forgetting some silly detail.  Anyway, we'll wait for expertise from @SylvainCorlay 👍

**Comment by joaander** [comment]
I'm not @SylvainCorlay, but this is a general problem with conda. It tries so hard to make installed packages relocatable that anything linked against libraries don't work unless they are installed in the conda root or fixed up by the conda-build process.

I work around this by using install_name_tool to fixup the library linkage during development. Here is a cmake macro that can fix a target.
```
#############################################################################################
# Fixup conda linking, if this python appears to be a conda python
get_filename_component(_python_bin_dir ${PYTHON_EXECUTABLE} DIRECTORY)
if (EXISTS "${_python_bin_dir}/conda")
    message("-- Detected conda python, activating workaround")
    set(_using_conda On)
else()
    set(_using_conda Off)
endif()

macro(fix_conda_python target)
if (_using_conda)
get_filename_component(_python_lib_file ${PYTHON_LIBRARY} NAME)
add_custom_command(TARGET ${target} POST_BUILD
                          COMMAND install_name_tool ARGS -change ${_python_lib_file} ${PYTHON_LIBRARY} $<TARGET_FILE:${target}>)
endif ()
endmacro()
```

**Comment by cjrh** [comment]
@joaander I've also used `install_name_tool` a fair bit in the past. How do you use this cmake macro with pybind11?

**Comment by SylvainCorlay** [comment]
Sorry for the late reply. I have not tried building the examples in an environment, so I will probably not be able to give you an educated answer as of now, but I will definitely take a look tomorrow.

**Comment by joaander** [comment]
I apply the macro to the .so library target that is the importable c library. I have not yet tried it with pybind11, but have used it in the past successfully with both boost::python and cython.

To see the macro in context in a cython based project:
https://bitbucket.org/glotzer/gsd/src/c98f2faef7027fa040e3a6bb796d7cb8066a3a83/CMake/PythonSetup.cmake?at=master&fileviewer=file-view-default

https://bitbucket.org/glotzer/gsd/src/c98f2faef7027fa040e3a6bb796d7cb8066a3a83/gsd/CMakeLists.txt?at=master&fileviewer=file-view-default

Sorry, I have no open source examples using it for boost::python or pybind11 yet.

**Comment by cjrh** [comment]
@SylvainCorlay This is not at all urgent for me so it's really no problem if you wait for a good opportunity to look at it.

@joaander Thanks for the links 👏

**Comment by wjakob** [comment]
@SylvainCorlay @cjrh : any news on this ticket? Are there some action items, or should it be closed?

**Comment by SylvainCorlay** [comment]
More documentation on relocatability in conda http://conda.pydata.org/docs/building/meta-yaml.html#making-packages-relocatable

**Comment by aldanor** [comment]
Late to join, but could someone explain in short what's the problem here?

I've built/packaged a few pybind11 packages with conda that are relocatable just fine.

**Comment by cjrh** [comment]
@wjakob I'm closing this this ticket.  There are a bunch of new things for me to try (thanks everyone!), and since I'm not using pybind in any active projects currently, it is not urgent.  

@aldanor Thanks for the tip!  I'll try that.  Do you know whether those flags work the same on OS X/clang?  Anyhow, I guess I'll find out when I get around to trying this out again.

Thanks again everyone for your help.

**Pull request closed without merging**
