### PR TITLE
fix: support sysconfig direclty in 3.10+

### LINKED ISSUE #3677: [BUG]: Distutils is going to be deprecated with Python3.12
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### Problem description

In Python 3.12 distutils is going to be removed and with 3.10 it's marked as deprecated. Currently `tools/FindPythonLibsNew.cmake` is still using

["${PYTHON_EXECUTABLE}" "-c" "from distutils import sysconfig as s;import sys;import struct;](https://github.com/pybind/pybind11/blob/ce18721d830a9deb8cf1883b513bcb8f98090c35/tools/FindPythonLibsNew.cmake#L115)

It might be replaceable by a simple `import sysconfig as s;`

See [[0]](https://docs.python.org/3/whatsnew/3.10.html#distutils-deprecated) and [[1]](https://docs.python.org/3/library/distutils.html)

Kind regards,
Arno

### Reproducible example code

_No response_

### PR DESCRIPTION
**Pull request by henryiii**
## Description

Closes #3677.

## Suggested changelog entry:

```rst
* Use sysconfig over distutils for Python 3.10 using classic CMake discovery.
```

### CODE REVIEW

**Review by rwgk — APPROVED** [review]
This seems to be very similar to a recent change in tools/pybind11NewTools.cmake. Evidently, someone works on one copy, unaware of the other, and it takes two iterations. I usually flag such situations with a comment, e.g.
```
# Note that there is similar code in X.
```

**Comment by henryiii** [comment]
This is a lot more complicated because we'll have to work out how to get each value, and have some sort of nicer toggle to keep the code from exploding. (notice it doesn't work on Python 3.10 with the current change) The pybind11NewTools.cmake change is only partially related.

**Comment by henryiii** [comment]
(pytorch/pytorch@4b96fc0 will likely be very helpful)

Given that nothing is broken, I think we are fine to continue with a release without doing this.

**Comment by stefanor** [comment]
Filed PR #3764, which adds a sysconfig path for >= 3.10, and uses the distutils mechanism for older pythons.

**Pull request closed without merging**
