### PR TITLE
Improving support for installing pybind11.

### LINKED ISSUE #305: Make it easier to install pybind11 with CMake
When installing a Python module library which used pybind11 I got an error message similar to [this stackoverflow question][q] because the include paths become different after installing the binary.

As a header-only library I think if it would be better to either

1. mark the headers as private instead of public, or
1. change the value based on if it is used build-time or install-time:

Quoting the quote from [the SO answer][a]:
> Include directories usage requirements commonly differ between the build-tree and the install-tree. The BUILD_INTERFACE and INSTALL_INTERFACE generator expressions can be used to describe separate usage requirements based on the usage location. Relative paths are allowed within the INSTALL_INTERFACE expression and are interpreted relative to the installation prefix. For example:
>
>     target_include_directories(mylib PUBLIC
>       $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include/mylib>
>       $<INSTALL_INTERFACE:include/mylib>  # <prefix>/include/mylib
>     ) 

[q]: http://stackoverflow.com/q/25676277/245614
[a]: http://stackoverflow.com/a/25681179/245614

### PR DESCRIPTION
**Pull request by trygvis**
Mark the pybind11 headers as private to the target.

Fixes #305

### CODE REVIEW

**Comment by dean0x7d** [comment]
👍 
On a related note, perhaps `PYTHON_INCLUDE_DIRS` should also be marked private.
Unless I'm overlooking something, the pybind11 module should always be a leaf target, so nothing will be able to make use of its interface properties anyway.

**Comment by wjakob** [comment]
Can you explain how/why the PUBLIC/PRIVATE difference matters here? (i.e. what issue does this PR fix).

Since Python plugin modules won't be linked into any other executables/applications, I fail to see how it matters.

**Comment by wjakob** [comment]
I looked at your ticket #305 but am not sure I follow. Can you provide an example of the install command you mention that causes these Cmake errors?

**Comment by dean0x7d** [comment]
As far as I understand, the CMake script would look like this:
```cmake
pybind11_add_module(my_module ...)
install(TARGETS my_module ...)  # installs the compiled binary
# error because it can't find the PUBLIC pybind11 headers in the `my_module` install location
```
But the installed binary doesn't actually need the headers, so they might as well be private.

**Comment by wjakob** [comment]
So it would actually try to copy the pybind11 header files? What about the Python header files?

**Comment by dean0x7d** [comment]
It's mostly just a nasty error message because the absolute path given to `target_include_directories` is not portable, i.e. it's relative to the cmake source path instead of the install path. The Python headers are in a system location (not relative to the cmake source dir), so they're not flagged by the error. I think that marking both pybind11 and Python headers as private would remove any future issues.

**Comment by wjakob** [comment]
That sounds good to me then, thanks for the clarification!

**Pull request merged**
