### PR TITLE
ci: test pypy 3.9

### PR DESCRIPTION
**Pull request by henryiii**
## Description

Trying out pypy 3.9

## Suggested changelog entry:

```rst

```

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Comment by henryiii** [comment]
I think we need to see if the FindPython mode works...

**Comment by Skylion007** [comment]
@henryiii Does our CI Tests not cover that?

**Comment by henryiii** [comment]
Only a few jobs do, with it injected via `include:`.

**Comment by henryiii** [comment]
(Even though it's not showing up here, CI is running)

**Pull request merged**
