### PR TITLE
PyPy3 support

### PR DESCRIPTION
**Pull request by isuruf**
1. Enable dynamic attribute support for PyPy >=6 from #1494 and added a test
2. Disabled `eval_file` as in https://github.com/pybind/pybind11/pull/1720#issuecomment-500559652
3. Workaround for `__qualname__` on PyPy3
4. Disabled numpy, scipy testing on PyPy as they fail to install.

TODO:
- [ ] Add a workaround for https://bitbucket.org/pypy/pypy/issues/2482/cpyext-tp_basicsize-only-considers-first. @jagerman added a workaround in #693, but that seems to work only for PyPy 5.8 and not even PyPy 5.9. See #1130

- [ ] Fix `test_stl_caster_vs_stl_bind`

cc @mattip, @ax3l

### CODE REVIEW

**Comment by isuruf** [comment]
`test_stl_caster_vs_stl_bind` issue is because `sq_item` is not being set even though `__getitem__` is set for the type `VectorInt`.

**Comment by isuruf** [comment]
Maybe defining `__getitem__` doesn't automatically set the value `sq_item` in PyPy.

**Comment by mattip** [comment]
> Maybe defining `__getitem__` doesn't automatically set the value `sq_item` in PyPy

It should, as long as `__getitem__` is set before calling `PyType_Ready`

**Comment by isuruf** [comment]
> It should, as long as __getitem__ is set before calling PyType_Ready

Ah, thanks. I think `__getitem__` gets defined after `PyType_Ready` is called. 

`PyType_Ready` is called by `make_new_python_type` which is called by `generic_type::initialize` method which is called by `class_` constructor and the `__getitem__` method is added by `class_::def` methof.

Somebody more familiar with `pybind11` internals should confirm though.

**Comment by inducer** [comment]
Slightly off-topic: @isuruf, could you please keep this branch around for a bit? I'm using it [here](https://gitlab.tiker.net/inducer/ci-support/-/commit/f5eae7ebef125d56d51b812184875643c7bfb350).

**Comment by ax3l** [comment]
cc @wjakob @jagerman this PR is needs some feedback on its way to add PyPy3.6 support, please.

**Comment by isuruf** [comment]
ping

**Comment by wjakob** [comment]
Ok, so what kind of feedback do you require? It's been ages since I looked at PyPy internals, so I don't think I could help much wit that. The patch looks reasonable to me, but I suppose it does not fully work yet?

**Comment by wjakob** [comment]
Regarding ``__getitem__`` et al.: when pybind11 adds an overload for methods, CPython will auto-detect that and populate the python type fields. So it's not necessary to add them before `PyType_Ready`. It is of course possible that PyPy is not consistent with CPython behavior.

**Comment by isuruf** [comment]
@mattip, is it possible to call `PyType_Ready` multiple times? We can't run `PyType_Ready` after everything due to the way pybind11 is designed unless we make the user call it explicitly after adding all the methods which would break existing code.

**Comment by mattip** [comment]
> is it possible to call `PyType_Ready` multiple times?

It is not an error but such calls are a no-op. The effect of `PyType_Ready` is to freeze the C-struct assignments. Any subsequent modifications should go through a C-API call, and not by directly setting a pointer from C.

@isuruf can you point me to the relevant code?

**Comment by isuruf** [comment]
See my comment at https://github.com/pybind/pybind11/pull/2146#issuecomment-604245873

Basically `class_`'s parent class' constructor at https://github.com/pybind/pybind11/blob/fb910ae92b4a489e9b31f9ec545bde9d09d6a40e/include/pybind11/pybind11.h#L887 calls https://github.com/pybind/pybind11/blob/dc65d661718ed10a9d212f1949813f7a7acf9437/include/pybind11/detail/class.h#L530 which calls PyType_Ready at https://github.com/pybind/pybind11/blob/dc65d661718ed10a9d212f1949813f7a7acf9437/include/pybind11/detail/class.h#L618

This particular example is at https://github.com/pybind/pybind11/blob/e97c735fc44bd39b390a321a276f41b3095ea2fe/include/pybind11/stl_bind.h#L113 where a `Class_` is passed in and the `__getitem__` is method is defined at https://github.com/pybind/pybind11/blob/e97c735fc44bd39b390a321a276f41b3095ea2fe/include/pybind11/stl_bind.h#L219

**Comment by mattip** [comment]
The problem is not `PyType_Ready`, rather that the assignment does not seem to reach `PyObject_SetAttrString`. 

I got to this assignment [`attr(cf.name()) = cf;`](https://github.com/pybind/pybind11/blob/e97c735fc44bd39b390a321a276f41b3095ea2fe/include/pybind11/pybind11.h#L1120), which assigns the new function to the class attribute `__getitem__` but I that does not seem to reach the [`setattr` call](https://github.com/pybind/pybind11/blob/e97c735fc44bd39b390a321a276f41b3095ea2fe/include/pybind11/pytypes.h#L438) in `pytypes.h`. How does this work on CPython? Does it depend on the `_PyObject_GetDictPtr` call returning the class dictionary (xref [this PyPy issue](https://bitbucket.org/pypy/pypy/issues/2447/cpyext-_pyobject_getdictptr-is) which is still open)

<details><summary>How I set the breakpoints</summary>

- From the top-level directory of pybind11, create the makefile
  ```
  cmake -DPYTHON_EXECUTABLE:FILEPATH=<path/to/pypy/exe \
  -DPYBIND11_PYTHON_VERSION=3.6 -DPYBIND11_CPP_STANDARD=-std=c++11 \
  -DPYBIND11_WERROR=ON -DDOWNLOAD_CATCH=ON \
  -DCMAKE_BUILD_TYPE=Debug .
  ```
- Run `make pytest -j2` to build everything. This will also take a while to run the tests.
- Start PyPy under the debugger `gdb <path/to/pypy>`
- Run the import once so the debugger can see the code `>>>> from pybind11_tests import local_bindings as m`
- Set the breakpoints `b pytypes.h:438` and `b pybind11.h:1120`
- Condition the breakpoints on `__getitem__`:
  ```
  condition 2 name_[0] == '_' & name_[2] == 'g' & name_[4] == 't'
  condition 1 name[0] == '_' & name[2] == 'g' & name[4] == 't'
  ```

**Comment by mattip** [comment]
I also wrote a little test for PyPy that checks calling `PyObject_SetAttrString` for `__getitem__` actually does work: and it passed.

**Comment by isuruf** [comment]
@mattip, `attr` call would reach https://github.com/pybind/pybind11/blob/e97c735fc44bd39b390a321a276f41b3095ea2fe/include/pybind11/pytypes.h#L434 not the function 4 lines below.

**Comment by mattip** [comment]
The failing test is the last line of the following test, where the line before succeeds (`__getitem__` **does** exist on `v1`)
```
from pybind11_tests import local_bindings as m
import pybind11_cross_module_tests as cm 
v1 = cm.VectorInt([1, 2, 3]);
print([v1[i] for i in range(3)]) 
print(m.load_vector_via_caster(v1))

TypeError: 'VectorInt' object does not support indexing
```

It turns out line 434, as @isuruf pionted out, is hit and the `__getitem__` attribute is set properly. Using a print rather than gdb proved it. 

Something else is at play, I am not sure what. Now I am diving into `load_vector_via_caster`

**Comment by mattip** [comment]
For `__getitem__`, it turns out to be a problem with the way PyPy was calling `PySequence_ITEM`. Fixed in [d7b55a353](https://foss.heptapod.net/pypy/pypy/commit/d7b55a353db34b733ebc5e5eb0176763864b6618). I could not write a concise test to reproduce, but the change seems to fix this problem.

**Comment by isuruf** [comment]
Thanks @mattip. One more issue to fix https://github.com/pybind/pybind11/pull/2146#issue-393892247. I'm afraid, you might be the best person to fix that as well.

**Comment by isuruf** [comment]
If I use the suggestion by @mattip in https://bitbucket.org/pypy/pypy/issues/2482/cpyext-tp_basicsize-only-considers-first, I can get the test to pass, but it segfaults other tests.

https://bitbucket.org/pypy/pypy/commits/8175c5e20480 mentions that

> but perhaps we should support PyBaseObject_Type too?

**Comment by wjakob** [comment]
I'd like to briefly check in about the status of the PR -- are we stalled on landing improvements to PyPy? There are already some good improvements, so one option would be to merge part of the changes and leave the rest pending.

**Comment by isuruf** [comment]
Yes. I've marked a couple of tests (related to multiple inheritance) as `bug_in_pypy` until we can fix it in PyPy. (I'm not entirely sure it's a bug in PyPy, but it looks like it and @mattip can confirm)

CI is passing (with two expected failures), so we can merge right now to avoid any regressions in the future and work on fixing the multiple inheritance issue.

**Comment by wjakob** [comment]
Ok, will do as soon as the PR is merge-able (conflicts).

**Comment by isuruf** [comment]
This is ready now

**Comment by wjakob** [comment]
Merged, let's track future improvements in a separate PR.

**Comment by YannickJadoul** [comment]
Tests are failing on master, for some reason.

**Comment by bstaletic** [comment]
```
>       assert msg(exc_info.value) == "m.class_.Pet.__init__() must be called when overriding __init__"
E       assert --- actual / +++ expected
E         - Pet.__init__() must be called when overriding __init__
E         + m.class_.Pet.__init__() must be called when overriding __init__
E         ? +++++++++
```

So the raised exception looks different than on CPython...

**Comment by YannickJadoul** [comment]
Something something `__qualname__`?

**Comment by bstaletic** [comment]
Should we mess with `__qualname__` or instead do something like this:

    assert msg(exec_info.value) in [ cpython_error_string, pypy_error_string ]

**Comment by YannickJadoul** [comment]
> Should we mess with `__qualname__` or instead do something like this:
> 
> ```
> assert msg(exec_info.value) in [ cpython_error_string, pypy_error_string ]
> ```

Depends a bit on whether this is a PyPy thing, or whether it's a failure of pybind11 to not set `tp_name` correctly?

**Comment by bstaletic** [comment]
If I'm reading [this](https://github.com/pybind/pybind11/blob/master/include/pybind11/detail/class.h#L18) right, pybind11, since python 3.3 doesn't touch `__qualname__`.

**Pull request merged**
