### PR TITLE
Changing .clang-format `AlignConsecutiveAssignments` to `false` and applying to smart_holder code.

### PR DESCRIPTION
**Pull request by rwgk**
Applying new .clang-format config merged with PR #3067.

**All changes are automatic (clang-format). NO manual changes.**

### CODE REVIEW

**Comment by rwgk** [comment]
@Skylion007 did you have a suggestion for another .clang-format config change? Something to do with pointers?

**Comment by Skylion007** [comment]
Yeah, there was suggestions about where to align "pointer *" and "reference &" to be part of the type instead of part of the var.

**Comment by EricCousineau-TRI** [comment]
I love this PR as it stands! We cool with reviewing / merging this as-is? @henryiii?
Perhaps pointer alignment can be a follow-up PR?

**Comment by EricCousineau-TRI** [comment]
Aha! I see #3065

**Comment by rwgk** [comment]
Ignoring the one CI flake (eigen download failed).

**Comment by rwgk** [comment]
Ouch, silly mistake: I forgot the `-a` in git commit :-(
I'll try again.

**Pull request merged**
